"""
LivingTreeAI - 生命之树AI集群系统
=========================

核心理念：算力民主化 + 知识共产化

技术选型（复用优先）:
- asyncio: 异步IO (内置)
- msgpack: 高效序列化 (已有)
- cryptography: 加密签名 (已有)
- py-utorrent-dht: Kademlia DHT (网络路由)
- aiortc: WebRTC NAT穿透
- networkx: 知识图谱
- numpy: 数值计算 (已有)

架构:
1. network/ - P2P网络层 (UDP发现 + TCP传输 + DHT路由)
2. knowledge/ - 知识共享层 (networkx图谱 + 联邦学习)
3. incentive/ - 激励层 (贡献证明 + 声誉系统)
4. task/ - 任务管理层 (暂停/恢复/取消)
5. identity/ - 身份管理层 (加密身份)

最低要求: 2GB RAM + 1Mbps网络 + 5GB存储

Author: LivingTreeAI Community
License: Apache 2.0
"""

__version__ = "1.0.0"
__author__ = "LivingTreeAI Community"

# 核心组件
from .node import LivingTreeNode, NodeStatus
from .network import P2PNetwork, NetworkConfig
from .knowledge import KnowledgeShare, KnowledgeType
from .federation import FederatedLearning, FLConfig
from .incentive import IncentiveSystem, ContributionRecord
from .protocol import MessageType, ProtocolHandler
from .task import TaskManager, Task, TaskStatus, TaskPriority

# 外脑调用系统
from .external_brain import (
    ChannelType,
    ChannelStatus,
    ChannelResult,
    ChannelManager,
    get_channel_manager,
    ServiceStatus,
    DiagnosisReport,
    NetworkDiagnoser,
    get_network_diagnoser,
    OfflineTask,
    OfflineQueue,
    get_offline_queue,
    ExternalBrainPanel,
    create_external_brain_panel,
)

# 四层通信协议栈
from .communication import (
    # 发现层
    NodeDiscovery,
    DiscoveryResult,
    DiscoveredNode,
    DiscoveryType,
    get_discovery,
    # 传输层
    NodeConnection,
    ConnectionStrategy,
    TransportType,
    NodeEndpoint,
    ConnectionInfo,
    get_transport,
    # 会话层
    NodeRPCServer,
    NodeRPCClient,
    MessageRouter,
    RPCRequest,
    RPCResponse,
    RPCError,
    get_rpc_server,
    # 安全层
    NoiseProtocol,
    SecurityContext,
    SecureChannel,
    get_security,
    # 服务端
    LifeTreeServer,
    LifeTreeClient,
    ServerConfig,
    start_server,
)

# 去中心化智慧网络
from .wisdom_network import (
    # 搜索网
    SearchRouter,
    SearchRequest,
    SearchResult,
    SpecialtyGraph,
    NodePerformanceStats,
    QueryContext,
    QueryCategory,
    get_search_router,
    # 缓存网
    DistributedCache,
    CacheEntry,
    CacheNotice,
    CacheRoutingTable,
    CacheHeatMap,
    get_distributed_cache,
    # 贡献网
    CreditNetwork,
    ContributionProof,
    ContributionLedger,
    ContributionType,
    ReputationScore,
    QuotaManager,
    get_credit_network,
    # 工作流
    WisdomNetwork,
    WisdomWorkflow,
    NetworkStats,
    get_wisdom_network,
)

# 三层同步体系
from .sync_network import (
    # 事件同步
    GossipSync,
    SyncEvent,
    EventType,
    SubscriptionManager,
    get_gossip_sync,
    # 增量同步
    IncrementalSync,
    VersionVector,
    MerkleTree,
    DataDigest,
    get_incremental_sync,
    # 全量同步
    FullSync,
    Snapshot,
    Shard,
    ShardStatus,
    get_full_sync,
    # 一致性
    ConsistencyModel,
    ConflictResolver,
    WriteOperation,
    ConsistencyLevel,
    get_consistency_model,
    # 管理器
    SyncManager,
    SyncConfig,
    SyncPartner,
    SyncStats,
    get_sync_manager,
)

__all__ = [
    # 节点
    "LivingTreeNode",
    "NodeStatus",
    # 网络
    "P2PNetwork",
    "NetworkConfig",
    # 知识
    "KnowledgeShare",
    "KnowledgeType",
    # 联邦学习
    "FederatedLearning",
    "FLConfig",
    # 激励
    "IncentiveSystem",
    "ContributionRecord",
    # 协议
    "MessageType",
    "ProtocolHandler",
    # 任务管理
    "TaskManager",
    "Task",
    "TaskStatus",
    "TaskPriority",
    # 外脑调用系统
    "ChannelType",
    "ChannelStatus",
    "ChannelResult",
    "ChannelManager",
    "get_channel_manager",
    "ServiceStatus",
    "DiagnosisReport",
    "NetworkDiagnoser",
    "get_network_diagnoser",
    "OfflineTask",
    "OfflineQueue",
    "get_offline_queue",
    "ExternalBrainPanel",
    "create_external_brain_panel",
    # 四层通信协议栈
    "NodeDiscovery",
    "DiscoveryResult",
    "DiscoveredNode",
    "DiscoveryType",
    "get_discovery",
    "NodeConnection",
    "ConnectionStrategy",
    "TransportType",
    "NodeEndpoint",
    "ConnectionInfo",
    "get_transport",
    "NodeRPCServer",
    "NodeRPCClient",
    "MessageRouter",
    "RPCRequest",
    "RPCResponse",
    "RPCError",
    "get_rpc_server",
    "NoiseProtocol",
    "SecurityContext",
    "SecureChannel",
    "get_security",
    "LifeTreeServer",
    "LifeTreeClient",
    "ServerConfig",
    "start_server",
    # 去中心化智慧网络
    "SearchRouter",
    "SearchRequest",
    "SearchResult",
    "SpecialtyGraph",
    "NodePerformanceStats",
    "QueryContext",
    "QueryCategory",
    "get_search_router",
    "DistributedCache",
    "CacheEntry",
    "CacheNotice",
    "CacheRoutingTable",
    "CacheHeatMap",
    "get_distributed_cache",
    "CreditNetwork",
    "ContributionProof",
    "ContributionLedger",
    "ContributionType",
    "ReputationScore",
    "QuotaManager",
    "get_credit_network",
    "WisdomNetwork",
    "WisdomWorkflow",
    "NetworkStats",
    "get_wisdom_network",
    # 三层同步体系
    "GossipSync",
    "SyncEvent",
    "EventType",
    "SubscriptionManager",
    "get_gossip_sync",
    "IncrementalSync",
    "VersionVector",
    "MerkleTree",
    "DataDigest",
    "get_incremental_sync",
    "FullSync",
    "Snapshot",
    "Shard",
    "ShardStatus",
    "get_full_sync",
    "ConsistencyModel",
    "ConflictResolver",
    "WriteOperation",
    "ConsistencyLevel",
    "get_consistency_model",
    "SyncManager",
    "SyncConfig",
    "SyncPartner",
    "SyncStats",
    "get_sync_manager",
    # 流媒体网络
    "WebRTCSFU",
    "StreamSession",
    "MediaTrack",
    "ConnectionState",
    "get_webrtc_sfu",
    "StreamingTopology",
    "TopologyType",
    "get_streaming_topology",
    "MediaSyncProtocol",
    "get_media_sync",
    "StreamStateSync",
    "get_stream_state_sync",
    "OptimisticConflictResolver",
    "get_conflict_resolver",
    "StreamQualityMonitor",
    "get_quality_monitor",
    # 神经层
    "NeuralPulseProtocol",
    "PulseType",
    "get_neural_pulse",
    "PrecognitiveLayer",
    "get_precognitive_layer",
    "ConsciousnessMerging",
    "get_consciousness_merger",
    "EmotionalEncoder",
    "EmotionVector",
    "get_emotional_encoder",
    "HolographicMessage",
    "get_holographic_messaging",
    "TimeFoldedMessage",
    "get_time_folded_messaging",
    "NeuralNetwork",
    "ConsciousnessState",
    "get_neural_network",
    # 分布式 AI 计算网络
    "CentralBrain",
    "IntentCollector",
    "InferenceNode",
    "NodeRegistry",
    "OverseasCluster",
    "EdgeAccelerator",
    "ContextEngine",
    "PolicyRouter",
    "ComplianceGateway",
    "TaskComposer",
    "NodeRole",
    "NodeStatus",
    "TaskType",
    "TaskStatus",
    "RoutingStrategy",
    "NodeInfo",
    "TaskRequest",
    "TaskResult",
    "ContextEntry",
    "create_brain",
    "create_client_collector",
    "create_overseas_cluster",
    "create_edge_node",
    # 深度匹配策略
    "MatchingDispatcher",
    "MatchingContext",
    "MatchingType",
    "MatchingResult",
    "AggregationMatcher",
    "DeepSearchMatcher",
    "SmartIDEMatcher",
    "SmartGameMatcher",
    "SmartBrowserMatcher",
    # 内部邮件系统
    "NodeIdentity",
    "create_node_identity",
    "MailMessage",
    "MailManager",
    "create_mail_manager",
    "MailTransport",
    "MailDatabase",
    "MessageRouter",
    "create_message_router",
    "DHTAttachmentStore",
    "MailAIEnhancer",
    "E2EEncryption",
    "MailSession",
    "MailFolder",
    "MessageType",
    "Attachment",
    "AttachmentStatus",
    # 智能工作空间
    "IntelligentWorkspace",
    "create_workspace",
    "ContentType",
    "PublishStatus",
    "ComplianceResult",
    "ContentCreator",
    "create_content_creator",
    "WritingTone",
    "ContentTemplate",
    "WebPublisher",
    "create_web_publisher",
    "PageType",
    "SEOOptimization",
    "CollaborationEngine",
    "create_collaboration_engine",
    "ReplyTone",
    "KnowledgeEntry",
    "SecurityGuard",
    "create_security_guard",
    "ThreatLevel",
    "ScanResult",
    "StorageEngine",
    "create_storage_engine",
    "StorageType",
    "IndexEntry",
    "PreviewCache",
    # 浏览器网关
    "BrowserGateway",
    "create_browser_gateway",
    "ProtocolHandler",
    "RPCBridge",
    "HyperOSProtocol",
    "HyperOSURI",
    "parse_hyperos_uri",
    "RPCInjector",
    "RPCMethod",
    "inject_window_hyperos",
    "OfflineMirror",
    "MirrorSnapshot",
    "create_offline_mirror",
    "CSSRewriter",
    "CSSRule",
    "create_css_rewriter",
    "CrawlerDispatcher",
    "CrawlTask",
    "create_crawler_dispatcher",
    # 分布式创作引擎
    "CreativeGenerator",
    "GenerationNode",
    "NodeCapability",
    "GenerationResult",
    "GenerationVersion",
    "create_distributed_generator",
    "BrowserIntegration",
    "SelectionContext",
    "GenerationRequest",
    "create_browser_integration",
    "ExecutionValidator",
    "ValidationResult",
    "SandboxResult",
    "create_execution_validator",
    "StyleMigrator",
    "StyleProfile",
    "KnowledgeEntry",
    "create_style_migrator",
    "CreativeGamification",
    "CreativeSpace",
    "CreativeNode",
    "Achievement",
    "create_gamification",
    # 环评智能工作台
    "EIAWorkbench",
    "ProjectConfig",
    "create_eia_workbench",
    "DocumentParser",
    "ParsedDocument",
    "ExtractedData",
    "create_document_parser",
    "SourceCalculator",
    "PollutionSource",
    "calculate_source_strength",
    "DrawingEngine",
    "DrawingLayer",
    "FlowChartNode",
    "ProtectionZone",
    "create_drawing_engine",
    "MapOverlay",
    "CoordinateSystem",
    "create_map_overlay",
    "ReportGenerator",
    "ReportSection",
    "create_report_generator",
    "ComplianceChecker",
    "ComplianceItem",
    "check_compliance",
    # 企业数字中台
    "EnterpriseDigitalTwin",
    "EnterpriseDimensions",
    "IdentityDimension",
    "PhysicalDimension",
    "PersonnelDimension",
    "BusinessProcessDimension",
    "AssetDimension",
    "ComplianceObligationDimension",
    "OperationalDataDimension",
    "RiskControlDimension",
    "get_enterprise_twin",
    "create_enterprise_twin_async",
    "ComplianceKnowledgeGraph",
    "KGNode",
    "KGEdge",
    "NodeType",
    "RelationType",
    "ComplianceCheckResult",
    "query_compliance_async",
    "build_enterprise_graph_async",
    "DeclarationPipeline",
    "DeclarationTask",
    "TaskStep",
    "PipelineStatus",
    "execute_declaration_async",
    "create_pipeline_async",
    "GovSiteAdapter",
    "SiteCapability",
    "FormField",
    "FormTemplate",
    "AutoFillResult",
    "get_adapter",
    "adapt_site_async",
    "RiskEarlyWarningEngine",
    "RiskAlert",
    "RiskLevel",
    "RiskCategory",
    "MonitorSource",
    "get_risk_engine",
    "check_risks_async",
    "subscribe_alerts_async",
    "EnterpriseOSController",
    "EnterpriseOSConfig",
    "LifecycleStage",
    "ComplianceTask",
    "TaskStatus",
    "get_enterprise_os",
    "create_enterprise_os_async",
    "execute_lifecycle_task_async",
]
