graph TD
    api___init__[__init__] --> api_routes[routes]
    api___init__[__init__] --> api_server[server]
    api_github_auth[github_auth] --> api_code_api[code_api]
    api_htmx_web[htmx_web] --> api_cognition_stream[cognition_stream]
    api_routes[routes] --> api_doc_routes[doc_routes]
    api_server[server] --> api_audit[audit]
    api_server[server] --> api_auth[auth]
    api_server[server] --> api_code_api[code_api]
    api_server[server] --> api_github_auth[github_auth]
    api_server[server] --> api_htmx_web[htmx_web]
    api_server[server] --> api_openai_proxy[openai_proxy]
    api_server[server] --> api_routes[routes]
    capability___init__[__init__] --> capability_ast_parser[ast_parser]
    capability___init__[__init__] --> capability_code_engine[code_engine]
    capability___init__[__init__] --> capability_code_graph[code_graph]
    capability___init__[__init__] --> capability_doc_engine[doc_engine]
    capability___init__[__init__] --> capability_document_intelligence[document_intelligence]
    capability___init__[__init__] --> capability_document_understanding[document_understanding]
    capability___init__[__init__] --> capability_extraction_engine[extraction_engine]
    capability___init__[__init__] --> capability_incremental_doc[incremental_doc]
    capability___init__[__init__] --> capability_material_collector[material_collector]
    capability___init__[__init__] --> capability_memory_pipeline[memory_pipeline]
    capability___init__[__init__] --> capability_multimodal_parser[multimodal_parser]
    capability___init__[__init__] --> capability_overnight_task[overnight_task]
    capability___init__[__init__] --> capability_pipeline_engine[pipeline_engine]
    capability___init__[__init__] --> capability_self_discovery[self_discovery]
    capability___init__[__init__] --> capability_skill_buckets[skill_buckets]
    capability___init__[__init__] --> capability_skill_discovery[skill_discovery]
    capability___init__[__init__] --> capability_skill_factory[skill_factory]
    capability___init__[__init__] --> capability_tool_market[tool_market]
    capability___init__[__init__] --> capability_unified_visual_port[unified_visual_port]
    capability_code_graph[code_graph] --> capability_ast_parser[ast_parser]
    capability_document_understanding[document_understanding] --> capability_document_intelligence[document_intelligence]
    capability_idle_consolidator[idle_consolidator] --> capability_adaptive_practice[adaptive_practice]
    capability_incremental_doc[incremental_doc] --> capability_document_intelligence[document_intelligence]
    capability_intelligence_collector[intelligence_collector] --> capability_adaptive_extractor[adaptive_extractor]
    capability_knowledge_forager[knowledge_forager] --> capability_intelligence_collector[intelligence_collector]
    capability_material_collector[material_collector] --> capability_document_processor[document_processor]
    capability_tool_market[tool_market] --> capability_browser_tools[browser_tools]
    capability_tool_market[tool_market] --> capability_tabular_reasoner[tabular_reasoner]
    capability_tool_meta[tool_meta] --> capability_tool_executor[tool_executor]
    capability_trend_radar[trend_radar] --> capability_material_collector[material_collector]
    capability_unified_file_tool[unified_file_tool] --> capability_code_graph[code_graph]
    cell___init__[__init__] --> cell_cell_ai[cell_ai]
    cell___init__[__init__] --> cell_distillation[distillation]
    cell___init__[__init__] --> cell_mitosis[mitosis]
    cell___init__[__init__] --> cell_phage[phage]
    cell___init__[__init__] --> cell_regen[regen]
    cell___init__[__init__] --> cell_registry[registry]
    cell___init__[__init__] --> cell_swift_trainer[swift_trainer]
    cell___init__[__init__] --> cell_trainer[trainer]
    cell_distillation[distillation] --> cell_cell_ai[cell_ai]
    cell_mitosis[mitosis] --> cell_cell_ai[cell_ai]
    cell_phage[phage] --> capability_ast_parser[ast_parser]
    cell_phage[phage] --> cell_cell_ai[cell_ai]
    cell_regen[regen] --> cell_cell_ai[cell_ai]
    cell_trainer[trainer] --> cell_swift_trainer[swift_trainer]
    config___init__[__init__] --> config_config_editor[config_editor]
    config___init__[__init__] --> config_config_security[config_security]
    config___init__[__init__] --> config_project_scaffold[project_scaffold]
    config___init__[__init__] --> config_secrets[secrets]
    config___init__[__init__] --> config_settings[settings]
    config_settings[settings] --> config_secrets[secrets]
    core___init__[__init__] --> core_adaptive_pipeline[adaptive_pipeline]
    core___init__[__init__] --> core_async_disk[async_disk]
    core___init__[__init__] --> core_entity_registry[entity_registry]
    core___init__[__init__] --> core_file_resolver[file_resolver]
    core___init__[__init__] --> core_hardware_acceleration[hardware_acceleration]
    core___init__[__init__] --> core_hardware_accelerator[hardware_accelerator]
    core___init__[__init__] --> core_jit_accel[jit_accel]
    core___init__[__init__] --> core_memory_optimizer[memory_optimizer]
    core___init__[__init__] --> core_system_orchestrator[system_orchestrator]
    core___init__[__init__] --> core_task_guard[task_guard]
    core___init__[__init__] --> core_unified_registry[unified_registry]
    core_admin_manager[admin_manager] --> config_secrets[secrets]
    core_autonomic_loop[autonomic_loop] --> core_action_principle[action_principle]
    core_awareness_engine[awareness_engine] --> core_auto_classifier[auto_classifier]
    core_launch[launch] --> config_settings[settings]
    core_launch[launch] --> core_action_principle[action_principle]
    core_launch[launch] --> core_autonomic_loop[autonomic_loop]
    core_seed_device[seed_device] --> capability_deadline_engine[deadline_engine]
    core_seed_device[seed_device] --> capability_knowledge_forager[knowledge_forager]
    core_system_health[system_health] --> core_decoupled_executor[decoupled_executor]
    core_system_orchestrator[system_orchestrator] --> capability_deadline_engine[deadline_engine]
    core_system_orchestrator[system_orchestrator] --> capability_knowledge_forager[knowledge_forager]
    core_system_orchestrator[system_orchestrator] --> capability_light_crawler[light_crawler]
    core_system_orchestrator[system_orchestrator] --> capability_needs_clarifier[needs_clarifier]
    core_system_orchestrator[system_orchestrator] --> capability_sub_agent_dispatch[sub_agent_dispatch]
    core_system_orchestrator[system_orchestrator] --> core_adaptive_pipeline[adaptive_pipeline]
    core_unified_registry[unified_registry] --> capability_tool_market[tool_market]
    core_universal_scanner[universal_scanner] --> core_admin_manager[admin_manager]
    core_voice_call[voice_call] --> core_llamacpp_backend[llamacpp_backend]
    core_voice_call[voice_call] --> core_moss_tts_engine[moss_tts_engine]
    core_voice_call[voice_call] --> core_unified_speech[unified_speech]
    dna___init__[__init__] --> dna_agent_roles[agent_roles]
    dna___init__[__init__] --> dna_autonomous_core[autonomous_core]
    dna___init__[__init__] --> dna_cache_optimizer[cache_optimizer]
    dna___init__[__init__] --> dna_consciousness[consciousness]
    dna___init__[__init__] --> dna_conversation_dna[conversation_dna]
    dna___init__[__init__] --> dna_dual_consciousness[dual_consciousness]
    dna___init__[__init__] --> dna_evolution[evolution]
    dna___init__[__init__] --> dna_evolution_store[evolution_store]
    dna___init__[__init__] --> dna_genome[genome]
    dna___init__[__init__] --> dna_gradual_agent[gradual_agent]
    dna___init__[__init__] --> dna_hitl[hitl]
    dna___init__[__init__] --> dna_life_engine[life_engine]
    dna___init__[__init__] --> dna_living_world[living_world]
    dna___init__[__init__] --> dna_local_intelligence[local_intelligence]
    dna___init__[__init__] --> dna_meta_memory[meta_memory]
    dna___init__[__init__] --> dna_meta_strategy[meta_strategy]
    dna___init__[__init__] --> dna_model_spec[model_spec]
    dna___init__[__init__] --> dna_output_compressor[output_compressor]
    dna___init__[__init__] --> dna_reasoning_chain[reasoning_chain]
    dna___init__[__init__] --> dna_safety[safety]
    dna___init__[__init__] --> dna_security_context[security_context]
    dna___init__[__init__] --> dna_self_evolving[self_evolving]
    dna___init__[__init__] --> dna_self_evolving_rules[self_evolving_rules]
    dna___init__[__init__] --> dna_skill_progression[skill_progression]
    dna___init__[__init__] --> dna_thought_harvest[thought_harvest]
    dna___init__[__init__] --> dna_tool_repair[tool_repair]
    dna_advanced[advanced] --> cell_regen[regen]
    dna_autonomous_learner[autonomous_learner] --> capability_web_reach[web_reach]
    dna_dual_consciousness[dual_consciousness] --> core_model_spec[model_spec]
    dna_dual_consciousness[dual_consciousness] --> dna_consciousness[consciousness]
    dna_life_daemon[life_daemon] --> cell_cell_ai[cell_ai]
    dna_life_daemon[life_daemon] --> cell_mitosis[mitosis]
    dna_life_daemon[life_daemon] --> dna_advanced[advanced]
    dna_life_daemon[life_daemon] --> dna_autonomous_core[autonomous_core]
    dna_life_daemon[life_daemon] --> dna_genome[genome]
    dna_life_engine[life_engine] --> core_entity_registry[entity_registry]
    dna_life_engine[life_engine] --> dna_consciousness[consciousness]
    dna_life_engine[life_engine] --> dna_genome[genome]
    dna_living_world[living_world] --> dna_consciousness[consciousness]
    dna_living_world[living_world] --> dna_genome[genome]
    dna_meta_strategy[meta_strategy] --> dna_meta_memory[meta_memory]
    dna_personality[personality] --> dna_adaptive_ui[adaptive_ui]
    dna_personality[personality] --> dna_anticipatory[anticipatory]
    dna_personality[personality] --> dna_biorhythm[biorhythm]
    dna_prompt_optimizer[prompt_optimizer] --> dna_model_spec[model_spec]
    dna_self_evolving[self_evolving] --> core_atomic_modification[atomic_modification]
    dna_self_evolving[self_evolving] --> dna_meta_memory[meta_memory]
    dna_self_evolving[self_evolving] --> dna_meta_strategy[meta_strategy]
    dna_tui_orchestrator[tui_orchestrator] --> dna_response_parser[response_parser]
    dna_tui_orchestrator[tui_orchestrator] --> dna_response_schemas[response_schemas]
    dna_unified_skill_system[unified_skill_system] --> core_async_disk[async_disk]
    dna_unified_skill_system[unified_skill_system] --> dna_meta_memory[meta_memory]
    dna_unified_skill_system[unified_skill_system] --> dna_skill_graph[skill_graph]
    dna_unified_skill_system[unified_skill_system] --> dna_skill_self_learn[skill_self_learn]
    economy___init__[__init__] --> economy_economic_engine[economic_engine]
    execution___init__[__init__] --> execution_batch_executor[batch_executor]
    execution___init__[__init__] --> execution_checkpoint[checkpoint]
    execution___init__[__init__] --> execution_continuation[continuation]
    execution___init__[__init__] --> execution_cost_aware[cost_aware]
    execution___init__[__init__] --> execution_dag_executor[dag_executor]
    execution___init__[__init__] --> execution_diffusion_planner[diffusion_planner]
    execution___init__[__init__] --> execution_fitness_landscape[fitness_landscape]
    execution___init__[__init__] --> execution_hitl[hitl]
    execution___init__[__init__] --> execution_orchestrator[orchestrator]
    execution___init__[__init__] --> execution_plan_validator[plan_validator]
    execution___init__[__init__] --> execution_quality_checker[quality_checker]
    execution___init__[__init__] --> execution_react_executor[react_executor]
    execution___init__[__init__] --> execution_real_pipeline[real_pipeline]
    execution___init__[__init__] --> execution_rlm[rlm]
    execution___init__[__init__] --> execution_self_healer[self_healer]
    execution___init__[__init__] --> execution_session_manager[session_manager]
    execution___init__[__init__] --> execution_side_git[side_git]
    execution___init__[__init__] --> execution_sub_agent_roles[sub_agent_roles]
    execution___init__[__init__] --> execution_task_planner[task_planner]
    execution___init__[__init__] --> execution_thinking_evolution[thinking_evolution]
    execution_checkpoint[checkpoint] --> core_task_guard[task_guard]
    execution_context_fold[context_fold] --> dna_output_compressor[output_compressor]
    execution_context_fold[context_fold] --> execution_context_codex[context_codex]
    execution_cron_scheduler[cron_scheduler] --> core_async_disk[async_disk]
    execution_dag_executor[dag_executor] --> execution_context_fold[context_fold]
    execution_panel_agent[panel_agent] --> dna_unified_skill_system[unified_skill_system]
    execution_quality_checker[quality_checker] --> dna_safety[safety]
    execution_react_executor[react_executor] --> dna_evolution[evolution]
    execution_real_pipeline[real_pipeline] --> capability_web_reach[web_reach]
    execution_real_pipeline[real_pipeline] --> core_task_guard[task_guard]
    execution_real_pipeline[real_pipeline] --> execution_auto_skill_resolver[auto_skill_resolver]
    execution_rlm[rlm] --> execution_context_fold[context_fold]
    execution_self_healer[self_healer] --> cell_regen[regen]
    execution_terminal_compressor[terminal_compressor] --> execution_global_rule_pool[global_rule_pool]
    execution_thinking_evolution[thinking_evolution] --> dna_meta_memory[meta_memory]
    execution_thinking_evolution[thinking_evolution] --> execution_quality_scorer[quality_scorer]
    execution_tool_router[tool_router] --> execution_context_fold[context_fold]
    execution_treeflow_planner[treeflow_planner] --> execution_gtsm_planner[gtsm_planner]
    execution_unified_pipeline[unified_pipeline] --> core_behavior_tree[behavior_tree]
    execution_unified_pipeline[unified_pipeline] --> execution_dag_executor[dag_executor]
    execution_unified_pipeline[unified_pipeline] --> execution_gtsm_planner[gtsm_planner]
    execution_unified_pipeline[unified_pipeline] --> execution_react_executor[react_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_compaction_executor[compaction_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_discard_executor[discard_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_disco_gc[disco_gc]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_gc_scheduler[gc_scheduler]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_bridge[storage_bridge]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_config[storage_config]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_trace_collector[trace_collector]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_faiss_backend[faiss_backend]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_memory_backend[memory_backend]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_sqlite_backend[sqlite_backend]
    infrastructure_storage_backends_faiss_backend[faiss_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_faiss_backend[faiss_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_backends_memory_backend[memory_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_memory_backend[memory_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_backends_sqlite_backend[sqlite_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_sqlite_backend[sqlite_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_disco_gc[disco_gc] --> infrastructure_storage_compaction_executor[compaction_executor]
    infrastructure_storage_disco_gc[disco_gc] --> infrastructure_storage_discard_executor[discard_executor]
    infrastructure_storage_gc_scheduler[gc_scheduler] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_storage_bridge[storage_bridge] --> infrastructure_storage_disco_gc[disco_gc]
    infrastructure_storage_storage_layer[storage_layer] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_trace_collector[trace_collector] --> infrastructure_storage_gc_metrics[gc_metrics]
    integration___init__[__init__] --> integration_hub[hub]
    integration___init__[__init__] --> integration_launcher[launcher]
    integration___init__[__init__] --> integration_message_gateway[message_gateway]
    integration___init__[__init__] --> integration_self_updater[self_updater]
    integration___init__[__init__] --> integration_sms_gateway[sms_gateway]
    integration___init__[__init__] --> integration_sse_server[sse_server]
    integration___init__[__init__] --> integration_unified_notifier[unified_notifier]
    integration___init__[__init__] --> integration_wechat_notifier[wechat_notifier]
    integration_hub[hub] --> capability_adaptive_practice[adaptive_practice]
    integration_hub[hub] --> capability_agent_marketplace[agent_marketplace]
    integration_hub[hub] --> capability_code_engine[code_engine]
    integration_hub[hub] --> capability_data_lineage[data_lineage]
    integration_hub[hub] --> capability_extraction_engine[extraction_engine]
    integration_hub[hub] --> capability_idle_consolidator[idle_consolidator]
    integration_hub[hub] --> capability_memory_pipeline[memory_pipeline]
    integration_hub[hub] --> capability_multimodal_parser[multimodal_parser]
    integration_hub[hub] --> capability_network_brain[network_brain]
    integration_hub[hub] --> capability_overnight_task[overnight_task]
    integration_hub[hub] --> capability_pipeline_engine[pipeline_engine]
    integration_hub[hub] --> capability_progressive_trust[progressive_trust]
    integration_hub[hub] --> capability_remote_assist[remote_assist]
    integration_hub[hub] --> capability_self_discovery[self_discovery]
    integration_hub[hub] --> capability_session_continuity[session_continuity]
    integration_hub[hub] --> capability_skill_buckets[skill_buckets]
    integration_hub[hub] --> capability_skill_discovery[skill_discovery]
    integration_hub[hub] --> capability_spark_search[spark_search]
    integration_hub[hub] --> capability_tool_market[tool_market]
    integration_hub[hub] --> capability_web_reach[web_reach]
    integration_hub[hub] --> config_project_scaffold[project_scaffold]
    integration_hub[hub] --> config_secrets[secrets]
    integration_hub[hub] --> core_async_disk[async_disk]
    integration_hub[hub] --> core_autonomous_growth[autonomous_growth]
    integration_hub[hub] --> core_capability_scanner[capability_scanner]
    integration_hub[hub] --> core_entity_registry[entity_registry]
    integration_hub[hub] --> core_memory_optimizer[memory_optimizer]
    integration_hub[hub] --> core_perf_accel[perf_accel]
    integration_hub[hub] --> core_resilience_brain[resilience_brain]
    integration_hub[hub] --> core_shell_env[shell_env]
    integration_hub[hub] --> core_task_guard[task_guard]
    integration_hub[hub] --> dna_adaptive_ui[adaptive_ui]
    integration_hub[hub] --> dna_agent_roles[agent_roles]
    integration_hub[hub] --> dna_anticipatory[anticipatory]
    integration_hub[hub] --> dna_autonomous_learner[autonomous_learner]
    integration_hub[hub] --> dna_biorhythm[biorhythm]
    integration_hub[hub] --> dna_cache_optimizer[cache_optimizer]
    integration_hub[hub] --> dna_conversation_dna[conversation_dna]
    integration_hub[hub] --> dna_dual_consciousness[dual_consciousness]
    integration_hub[hub] --> dna_evolution[evolution]
    integration_hub[hub] --> dna_evolution_store[evolution_store]
    integration_hub[hub] --> dna_hitl[hitl]
    integration_hub[hub] --> dna_life_daemon[life_daemon]
    integration_hub[hub] --> dna_multi_agent_debate[multi_agent_debate]
    integration_hub[hub] --> dna_predictive_world[predictive_world]
    integration_hub[hub] --> dna_self_narrative[self_narrative]
    integration_hub[hub] --> economy_economic_engine[economic_engine]
    integration_hub[hub] --> execution_batch_executor[batch_executor]
    integration_hub[hub] --> execution_cron_scheduler[cron_scheduler]
    integration_hub[hub] --> execution_react_executor[react_executor]
    integration_hub[hub] --> execution_real_pipeline[real_pipeline]
    integration_hub[hub] --> execution_rlm[rlm]
    integration_hub[hub] --> execution_session_manager[session_manager]
    integration_hub[hub] --> execution_side_git[side_git]
    integration_hub[hub] --> execution_sub_agent_roles[sub_agent_roles]
    integration_launcher[launcher] --> api_server[server]
    integration_launcher[launcher] --> cell_cell_ai[cell_ai]
    integration_launcher[launcher] --> integration_hub[hub]
    integration_self_updater[self_updater] --> integration_pkg_manager[pkg_manager]
    knowledge___init__[__init__] --> knowledge_agentic_rag[agentic_rag]
    knowledge___init__[__init__] --> knowledge_cognitive_delta[cognitive_delta]
    knowledge___init__[__init__] --> knowledge_content_quality[content_quality]
    knowledge___init__[__init__] --> knowledge_context_glossary[context_glossary]
    knowledge___init__[__init__] --> knowledge_document_tree[document_tree]
    knowledge___init__[__init__] --> knowledge_engram_store[engram_store]
    knowledge___init__[__init__] --> knowledge_format_discovery[format_discovery]
    knowledge___init__[__init__] --> knowledge_gap_detector[gap_detector]
    knowledge___init__[__init__] --> knowledge_hallucination_guard[hallucination_guard]
    knowledge___init__[__init__] --> knowledge_hierarchical_chunker[hierarchical_chunker]
    knowledge___init__[__init__] --> knowledge_ideablock_enricher[ideablock_enricher]
    knowledge___init__[__init__] --> knowledge_intelligent_kb[intelligent_kb]
    knowledge___init__[__init__] --> knowledge_knowledge_base[knowledge_base]
    knowledge___init__[__init__] --> knowledge_knowledge_graph[knowledge_graph]
    knowledge___init__[__init__] --> knowledge_knowledge_router[knowledge_router]
    knowledge___init__[__init__] --> knowledge_layout_analyzer[layout_analyzer]
    knowledge___init__[__init__] --> knowledge_learning_engine[learning_engine]
    knowledge___init__[__init__] --> knowledge_modern_ocr[modern_ocr]
    knowledge___init__[__init__] --> knowledge_multidoc_fusion[multidoc_fusion]
    knowledge___init__[__init__] --> knowledge_onto_bridge[onto_bridge]
    knowledge___init__[__init__] --> knowledge_pii_redactor[pii_redactor]
    knowledge___init__[__init__] --> knowledge_provenance[provenance]
    knowledge___init__[__init__] --> knowledge_quality_guard[quality_guard]
    knowledge___init__[__init__] --> knowledge_query_decomposer[query_decomposer]
    knowledge___init__[__init__] --> knowledge_relation_engine[relation_engine]
    knowledge___init__[__init__] --> knowledge_reranker[reranker]
    knowledge___init__[__init__] --> knowledge_retrieval_validator[retrieval_validator]
    knowledge___init__[__init__] --> knowledge_struct_mem[struct_mem]
    knowledge___init__[__init__] --> knowledge_vector_store[vector_store]
    knowledge_engram_store[engram_store] --> execution_context_codex[context_codex]
    knowledge_entity_bridge[entity_bridge] --> knowledge_context_glossary[context_glossary]
    knowledge_hierarchical_chunker[hierarchical_chunker] --> knowledge_document_tree[document_tree]
    knowledge_hypergraph_store[hypergraph_store] --> core_synaptic_plasticity[synaptic_plasticity]
    knowledge_intelligent_kb[intelligent_kb] --> capability_web_reach[web_reach]
    knowledge_intelligent_kb[intelligent_kb] --> core_async_disk[async_disk]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_document_kb[document_kb]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_engram_store[engram_store]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_hallucination_guard[hallucination_guard]
    knowledge_knowledge_base[knowledge_base] --> knowledge_dedup[dedup]
    knowledge_knowledge_base[knowledge_base] --> knowledge_engram_store[engram_store]
    knowledge_layout_analyzer[layout_analyzer] --> knowledge_document_tree[document_tree]
    knowledge_learning_engine[learning_engine] --> knowledge_knowledge_base[knowledge_base]
    knowledge_multidoc_fusion[multidoc_fusion] --> knowledge_document_tree[document_tree]
    knowledge_multidoc_fusion[multidoc_fusion] --> knowledge_hierarchical_chunker[hierarchical_chunker]
    knowledge_quality_guard[quality_guard] --> knowledge_hallucination_guard[hallucination_guard]
    knowledge_vector_store[vector_store] --> infrastructure_io_optimizer[io_optimizer]
    lsp___init__[__init__] --> lsp_lsp_manager[lsp_manager]
    market___init__[__init__] --> market_opportunity_scorer[opportunity_scorer]
    market___init__[__init__] --> market_revenue_engine[revenue_engine]
    market___init__[__init__] --> market_user_profile[user_profile]
    mcp___init__[__init__] --> mcp_server[server]
    mcp_server[server] --> capability_code_graph[code_graph]
    mcp_server[server] --> capability_tabular_reasoner[tabular_reasoner]
    mcp_server[server] --> integration_hub[hub]
    mcp_server[server] --> knowledge_engram_store[engram_store]
    mcp_server[server] --> knowledge_pii_redactor[pii_redactor]
    memory___init__[__init__] --> memory_memory_policy[memory_policy]
    memory___init__[__init__] --> memory_user_model[user_model]
    memory_user_model[user_model] --> execution_context_codex[context_codex]
    network___init__[__init__] --> network_biometric_signature[biometric_signature]
    network___init__[__init__] --> network_config_sync[config_sync]
    network___init__[__init__] --> network_discovery[discovery]
    network___init__[__init__] --> network_domain_ip_pool[domain_ip_pool]
    network___init__[__init__] --> network_encrypted_channel[encrypted_channel]
    network___init__[__init__] --> network_nat_traverse[nat_traverse]
    network___init__[__init__] --> network_node[node]
    network___init__[__init__] --> network_offline_mode[offline_mode]
    network___init__[__init__] --> network_p2p_node[p2p_node]
    network___init__[__init__] --> network_p2p_presence[p2p_presence]
    network___init__[__init__] --> network_presence_sensor[presence_sensor]
    network___init__[__init__] --> network_relay_registry[relay_registry]
    network___init__[__init__] --> network_reputation[reputation]
    network___init__[__init__] --> network_scinet_bandit[scinet_bandit]
    network___init__[__init__] --> network_scinet_cache[scinet_cache]
    network___init__[__init__] --> network_scinet_engine[scinet_engine]
    network___init__[__init__] --> network_scinet_federated[scinet_federated]
    network___init__[__init__] --> network_scinet_quic[scinet_quic]
    network___init__[__init__] --> network_scinet_service[scinet_service]
    network___init__[__init__] --> network_scinet_swarm[scinet_swarm]
    network___init__[__init__] --> network_scinet_topology[scinet_topology]
    network___init__[__init__] --> network_scinet_vllm[scinet_vllm]
    network___init__[__init__] --> network_scinet_webtransport[scinet_webtransport]
    network___init__[__init__] --> network_site_accelerator[site_accelerator]
    network___init__[__init__] --> network_spatial_awareness[spatial_awareness]
    network_offline_mode[offline_mode] --> knowledge_knowledge_base[knowledge_base]
    network_p2p_node[p2p_node] --> core_unified_registry[unified_registry]
    network_p2p_presence[p2p_presence] --> network_collective[collective]
    network_resilience[resilience] --> network_proxy_fetcher[proxy_fetcher]
    network_scinet_engine[scinet_engine] --> network_scinet_bandit[scinet_bandit]
    network_scinet_engine[scinet_engine] --> network_scinet_cache[scinet_cache]
    network_scinet_service[scinet_service] --> network_domain_ip_pool[domain_ip_pool]
    network_scinet_service[scinet_service] --> network_proxy_fetcher[proxy_fetcher]
    network_scinet_service[scinet_service] --> network_scinet_engine[scinet_engine]
    network_site_accelerator[site_accelerator] --> network_domain_ip_pool[domain_ip_pool]
    network_smart_dns[smart_dns] --> network_domain_ip_pool[domain_ip_pool]
    network_smart_dns[smart_dns] --> network_scinet_service[scinet_service]
    network_swarm_coordinator[swarm_coordinator] --> network_message_bus[message_bus]
    network_universal_pairing[universal_pairing] --> network_discovery[discovery]
    network_webrtc_remote[webrtc_remote] --> core_shell_env[shell_env]
    observability___init__[__init__] --> observability_activity_feed[activity_feed]
    observability___init__[__init__] --> observability_agent_eval[agent_eval]
    observability___init__[__init__] --> observability_audit_log[audit_log]
    observability___init__[__init__] --> observability_calibration[calibration]
    observability___init__[__init__] --> observability_change_manifest[change_manifest]
    observability___init__[__init__] --> observability_claim_checker[claim_checker]
    observability___init__[__init__] --> observability_error_replay[error_replay]
    observability___init__[__init__] --> observability_harness_registry[harness_registry]
    observability___init__[__init__] --> observability_logger[logger]
    observability___init__[__init__] --> observability_metrics[metrics]
    observability___init__[__init__] --> observability_sentinel[sentinel]
    observability___init__[__init__] --> observability_setup[setup]
    observability___init__[__init__] --> observability_tracer[tracer]
    observability___init__[__init__] --> observability_trust_scoring[trust_scoring]
    observability_error_replay[error_replay] --> capability_self_modifier[self_modifier]
    observability_setup[setup] --> observability_logger[logger]
    observability_setup[setup] --> observability_metrics[metrics]
    observability_tracer[tracer] --> observability_logger[logger]
    observability_trust_scoring[trust_scoring] --> observability_agent_eval[agent_eval]
    reasoning_dialectical___init__[__init__] --> reasoning_dialectical_contradiction_tracker[contradiction_tracker]
    reasoning_dialectical___init__[__init__] --> reasoning_dialectical_phase_transition[phase_transition]
    reasoning_formal___init__[__init__] --> reasoning_formal_rule_engine[rule_engine]
    reasoning_formal___init__[__init__] --> reasoning_formal_syllogism[syllogism]
    reasoning_historical___init__[__init__] --> reasoning_historical_attribution_loop[attribution_loop]
    reasoning_historical___init__[__init__] --> reasoning_historical_consensus_measure[consensus_measure]
    reasoning_historical___init__[__init__] --> reasoning_historical_layering_tracker[layering_tracker]
    reasoning_mathematical___init__[__init__] --> reasoning_mathematical_bayesian_reasoner[bayesian_reasoner]
    reasoning_mathematical___init__[__init__] --> reasoning_mathematical_knowledge_representation[knowledge_representation]
    serialization___init__[__init__] --> serialization_benchmark[benchmark]
    serialization___init__[__init__] --> serialization_protobuf_engine[protobuf_engine]
    serialization___init__[__init__] --> serialization_service_stubs[service_stubs]
    serialization_service_stubs[service_stubs] --> serialization_protobuf_engine[protobuf_engine]
    treellm___init__[__init__] --> treellm_classifier[classifier]
    treellm___init__[__init__] --> treellm_core[core]
    treellm___init__[__init__] --> treellm_embedding_scorer[embedding_scorer]
    treellm___init__[__init__] --> treellm_foresight_gate[foresight_gate]
    treellm___init__[__init__] --> treellm_holistic_election[holistic_election]
    treellm___init__[__init__] --> treellm_onto_prompt_builder[onto_prompt_builder]
    treellm___init__[__init__] --> treellm_prompt_versioning[prompt_versioning]
    treellm___init__[__init__] --> treellm_providers[providers]
    treellm___init__[__init__] --> treellm_route_learner[route_learner]
    treellm_bandit_router[bandit_router] --> core_synaptic_plasticity[synaptic_plasticity]
    treellm_cache_director[cache_director] --> dna_cache_optimizer[cache_optimizer]
    treellm_core[core] --> capability_industrial_doc_engine[industrial_doc_engine]
    treellm_core[core] --> dna_cache_optimizer[cache_optimizer]
    treellm_core[core] --> dna_unified_skill_system[unified_skill_system]
    treellm_core[core] --> network_p2p_node[p2p_node]
    treellm_core[core] --> observability_activity_feed[activity_feed]
    treellm_core[core] --> observability_trust_scoring[trust_scoring]
    treellm_core[core] --> treellm_cache_director[cache_director]
    treellm_core[core] --> treellm_classifier[classifier]
    treellm_gateway[gateway] --> treellm_core[core]
    treellm_holistic_election[holistic_election] --> treellm_cache_director[cache_director]
    treellm_model_registry[model_registry] --> treellm_models_dev_sync[models_dev_sync]
    treellm_mtp_drafter[mtp_drafter] --> execution_gtsm_planner[gtsm_planner]
    treellm_mtp_drafter[mtp_drafter] --> treellm_free_pool_manager[free_pool_manager]
    treellm_parallel_drafter[parallel_drafter] --> treellm_free_pool_manager[free_pool_manager]
    treellm_provider_registry[provider_registry] --> config_settings[settings]
    treellm_provider_registry[provider_registry] --> economy_economic_engine[economic_engine]
    treellm_provider_registry[provider_registry] --> treellm_free_pool_manager[free_pool_manager]
    treellm_provider_registry[provider_registry] --> treellm_holistic_election[holistic_election]
    treellm_route_learner[route_learner] --> execution_fitness_landscape[fitness_landscape]
    treellm_route_learner[route_learner] --> treellm_model_registry[model_registry]
    treellm_route_learner[route_learner] --> treellm_models_dev_sync[models_dev_sync]
    treellm_skill_router[skill_router] --> dna_skill_graph[skill_graph]