graph TD
    api___init__[__init__] --> api_routes[routes]
    api___init__[__init__] --> api_server[server]
    api_github_auth[github_auth] --> api_code_api[code_api]
    api_htmx_web[htmx_web] --> api_cognition_stream[cognition_stream]
    api_htmx_web[htmx_web] --> api_htmx_business[htmx_business]
    api_htmx_web[htmx_web] --> api_htmx_living[htmx_living]
    api_routes[routes] --> api_doc_routes[doc_routes]
    api_server[server] --> api_audit[audit]
    api_server[server] --> api_auth[auth]
    api_server[server] --> api_code_api[code_api]
    api_server[server] --> api_github_auth[github_auth]
    api_server[server] --> api_htmx_web[htmx_web]
    api_server[server] --> api_openai_proxy[openai_proxy]
    api_server[server] --> api_routes[routes]
    capability___init__[__init__] --> capability_ast_parser[ast_parser]
    capability___init__[__init__] --> capability_code_engine[code_engine]
    capability___init__[__init__] --> capability_code_graph[code_graph]
    capability___init__[__init__] --> capability_doc_engine[doc_engine]
    capability___init__[__init__] --> capability_document_intelligence[document_intelligence]
    capability___init__[__init__] --> capability_document_understanding[document_understanding]
    capability___init__[__init__] --> capability_extraction_engine[extraction_engine]
    capability___init__[__init__] --> capability_incremental_doc[incremental_doc]
    capability___init__[__init__] --> capability_material_collector[material_collector]
    capability___init__[__init__] --> capability_memory_pipeline[memory_pipeline]
    capability___init__[__init__] --> capability_multimodal_parser[multimodal_parser]
    capability___init__[__init__] --> capability_overnight_task[overnight_task]
    capability___init__[__init__] --> capability_pipeline_engine[pipeline_engine]
    capability___init__[__init__] --> capability_self_discovery[self_discovery]
    capability___init__[__init__] --> capability_skill_buckets[skill_buckets]
    capability___init__[__init__] --> capability_skill_discovery[skill_discovery]
    capability___init__[__init__] --> capability_skill_factory[skill_factory]
    capability___init__[__init__] --> capability_tool_market[tool_market]
    capability___init__[__init__] --> capability_unified_visual_port[unified_visual_port]
    capability___init__[__init__] --> capability_virtual_fs[virtual_fs]
    capability_code_graph[code_graph] --> capability_ast_parser[ast_parser]
    capability_doc_learner[doc_learner] --> capability_document_understanding[document_understanding]
    capability_document_understanding[document_understanding] --> capability_document_intelligence[document_intelligence]
    capability_idle_consolidator[idle_consolidator] --> capability_adaptive_practice[adaptive_practice]
    capability_incremental_doc[incremental_doc] --> capability_document_intelligence[document_intelligence]
    capability_intelligence_collector[intelligence_collector] --> capability_adaptive_extractor[adaptive_extractor]
    capability_knowledge_forager[knowledge_forager] --> capability_intelligence_collector[intelligence_collector]
    capability_material_collector[material_collector] --> capability_document_processor[document_processor]
    capability_multi_learner[multi_learner] --> capability_code_learner[code_learner]
    capability_multi_learner[multi_learner] --> capability_doc_learner[doc_learner]
    capability_tool_market[tool_market] --> capability_browser_tools[browser_tools]
    capability_tool_market[tool_market] --> capability_tabular_reasoner[tabular_reasoner]
    capability_tool_meta[tool_meta] --> capability_tool_executor[tool_executor]
    capability_tool_synthesis[tool_synthesis] --> capability_tool_registry[tool_registry]
    capability_trend_radar[trend_radar] --> capability_material_collector[material_collector]
    capability_unified_file_tool[unified_file_tool] --> capability_code_graph[code_graph]
    capability_unified_search[unified_search] --> capability_bing_search[bing_search]
    capability_unified_search[unified_search] --> capability_ddg_search[ddg_search]
    capability_unified_search[unified_search] --> capability_llm_web_search[llm_web_search]
    capability_unified_search[unified_search] --> capability_searxng_search[searxng_search]
    capability_unified_search[unified_search] --> capability_spark_search[spark_search]
    capability_virtual_fs[virtual_fs] --> capability_public_apis_resource[public_apis_resource]
    capability_world_explorer[world_explorer] --> capability_light_crawler[light_crawler]
    capability_zero_shot_tools[zero_shot_tools] --> capability_public_apis_resource[public_apis_resource]
    cell___init__[__init__] --> cell_cell_ai[cell_ai]
    cell___init__[__init__] --> cell_distillation[distillation]
    cell___init__[__init__] --> cell_mitosis[mitosis]
    cell___init__[__init__] --> cell_phage[phage]
    cell___init__[__init__] --> cell_regen[regen]
    cell___init__[__init__] --> cell_registry[registry]
    cell___init__[__init__] --> cell_swift_trainer[swift_trainer]
    cell___init__[__init__] --> cell_trainer[trainer]
    cell_distillation[distillation] --> cell_cell_ai[cell_ai]
    cell_dream_pretraining[dream_pretraining] --> capability_world_explorer[world_explorer]
    cell_mitosis[mitosis] --> cell_cell_ai[cell_ai]
    cell_phage[phage] --> capability_ast_parser[ast_parser]
    cell_phage[phage] --> cell_cell_ai[cell_ai]
    cell_regen[regen] --> cell_cell_ai[cell_ai]
    cell_trainer[trainer] --> cell_swift_trainer[swift_trainer]
    config___init__[__init__] --> config_config_editor[config_editor]
    config___init__[__init__] --> config_config_security[config_security]
    config___init__[__init__] --> config_project_scaffold[project_scaffold]
    config___init__[__init__] --> config_secrets[secrets]
    config___init__[__init__] --> config_settings[settings]
    config_settings[settings] --> config_secrets[secrets]
    core___init__[__init__] --> core_adaptive_pipeline[adaptive_pipeline]
    core___init__[__init__] --> core_async_disk[async_disk]
    core___init__[__init__] --> core_entity_registry[entity_registry]
    core___init__[__init__] --> core_file_resolver[file_resolver]
    core___init__[__init__] --> core_hardware_acceleration[hardware_acceleration]
    core___init__[__init__] --> core_hardware_accelerator[hardware_accelerator]
    core___init__[__init__] --> core_jit_accel[jit_accel]
    core___init__[__init__] --> core_memory_optimizer[memory_optimizer]
    core___init__[__init__] --> core_system_orchestrator[system_orchestrator]
    core___init__[__init__] --> core_task_guard[task_guard]
    core___init__[__init__] --> core_unified_registry[unified_registry]
    core_admin_manager[admin_manager] --> config_secrets[secrets]
    core_autonomic_loop[autonomic_loop] --> core_action_principle[action_principle]
    core_awareness_engine[awareness_engine] --> core_auto_classifier[auto_classifier]
    core_execution_pipeline[execution_pipeline] --> core_adaptive_folder[adaptive_folder]
    core_execution_pipeline[execution_pipeline] --> core_behavior_control[behavior_control]
    core_inline_parser[inline_parser] --> core_archive_preview[archive_preview]
    core_launch[launch] --> config_settings[settings]
    core_launch[launch] --> core_action_principle[action_principle]
    core_launch[launch] --> core_autonomic_loop[autonomic_loop]
    core_seed_device[seed_device] --> capability_deadline_engine[deadline_engine]
    core_seed_device[seed_device] --> capability_knowledge_forager[knowledge_forager]
    core_session_memory[session_memory] --> core_collective_intel[collective_intel]
    core_system_health[system_health] --> core_decoupled_executor[decoupled_executor]
    core_system_orchestrator[system_orchestrator] --> capability_deadline_engine[deadline_engine]
    core_system_orchestrator[system_orchestrator] --> capability_knowledge_forager[knowledge_forager]
    core_system_orchestrator[system_orchestrator] --> capability_light_crawler[light_crawler]
    core_system_orchestrator[system_orchestrator] --> capability_needs_clarifier[needs_clarifier]
    core_system_orchestrator[system_orchestrator] --> capability_sub_agent_dispatch[sub_agent_dispatch]
    core_system_orchestrator[system_orchestrator] --> core_adaptive_pipeline[adaptive_pipeline]
    core_unified_registry[unified_registry] --> capability_tool_market[tool_market]
    core_unified_registry[unified_registry] --> capability_tool_registry[tool_registry]
    core_universal_scanner[universal_scanner] --> core_admin_manager[admin_manager]
    core_voice_call[voice_call] --> core_llamacpp_backend[llamacpp_backend]
    core_voice_call[voice_call] --> core_moss_tts_engine[moss_tts_engine]
    core_voice_call[voice_call] --> core_unified_speech[unified_speech]
    dna___init__[__init__] --> dna_agent_roles[agent_roles]
    dna___init__[__init__] --> dna_autonomous_core[autonomous_core]
    dna___init__[__init__] --> dna_autonomous_goals[autonomous_goals]
    dna___init__[__init__] --> dna_cache_optimizer[cache_optimizer]
    dna___init__[__init__] --> dna_consciousness[consciousness]
    dna___init__[__init__] --> dna_conversation_dna[conversation_dna]
    dna___init__[__init__] --> dna_dual_consciousness[dual_consciousness]
    dna___init__[__init__] --> dna_evolution_store[evolution_store]
    dna___init__[__init__] --> dna_genome[genome]
    dna___init__[__init__] --> dna_gep_protocol[gep_protocol]
    dna___init__[__init__] --> dna_gradual_agent[gradual_agent]
    dna___init__[__init__] --> dna_hitl[hitl]
    dna___init__[__init__] --> dna_life_engine[life_engine]
    dna___init__[__init__] --> dna_living_world[living_world]
    dna___init__[__init__] --> dna_local_intelligence[local_intelligence]
    dna___init__[__init__] --> dna_meta_memory[meta_memory]
    dna___init__[__init__] --> dna_meta_strategy[meta_strategy]
    dna___init__[__init__] --> dna_model_spec[model_spec]
    dna___init__[__init__] --> dna_output_compressor[output_compressor]
    dna___init__[__init__] --> dna_reasoning_chain[reasoning_chain]
    dna___init__[__init__] --> dna_safety[safety]
    dna___init__[__init__] --> dna_security_context[security_context]
    dna___init__[__init__] --> dna_self_evolving[self_evolving]
    dna___init__[__init__] --> dna_self_evolving_rules[self_evolving_rules]
    dna___init__[__init__] --> dna_skill_progression[skill_progression]
    dna___init__[__init__] --> dna_thought_harvest[thought_harvest]
    dna___init__[__init__] --> dna_tool_repair[tool_repair]
    dna_advanced[advanced] --> cell_regen[regen]
    dna_auto_trainer[auto_trainer] --> cell_dream_learner[dream_learner]
    dna_auto_trainer[auto_trainer] --> cell_swift_trainer[swift_trainer]
    dna_auto_trainer[auto_trainer] --> cell_trainer[trainer]
    dna_autonomous_learner[autonomous_learner] --> capability_unified_search[unified_search]
    dna_autonomous_learner[autonomous_learner] --> capability_web_reach[web_reach]
    dna_biorhythm[biorhythm] --> cell_dream_pretraining[dream_pretraining]
    dna_dream_consolidation[dream_consolidation] --> cell_dream_pretraining[dream_pretraining]
    dna_dual_consciousness[dual_consciousness] --> core_model_spec[model_spec]
    dna_dual_consciousness[dual_consciousness] --> dna_consciousness[consciousness]
    dna_evolution_store[evolution_store] --> api_token_accountant[token_accountant]
    dna_expert_role_manager[expert_role_manager] --> capability_tool_registry[tool_registry]
    dna_hormone_signaling[hormone_signaling] --> core_synaptic_plasticity[synaptic_plasticity]
    dna_life_daemon[life_daemon] --> cell_cell_ai[cell_ai]
    dna_life_daemon[life_daemon] --> cell_mitosis[mitosis]
    dna_life_daemon[life_daemon] --> dna_advanced[advanced]
    dna_life_daemon[life_daemon] --> dna_autonomous_core[autonomous_core]
    dna_life_daemon[life_daemon] --> dna_genome[genome]
    dna_life_engine[life_engine] --> core_collective_intel[collective_intel]
    dna_life_engine[life_engine] --> dna_attention_budget[attention_budget]
    dna_life_engine[life_engine] --> dna_autonomous_goals[autonomous_goals]
    dna_life_engine[life_engine] --> dna_consciousness[consciousness]
    dna_life_engine[life_engine] --> dna_consciousness_emergence[consciousness_emergence]
    dna_life_engine[life_engine] --> dna_dream_consolidation[dream_consolidation]
    dna_life_engine[life_engine] --> dna_dream_engine[dream_engine]
    dna_life_engine[life_engine] --> dna_emotion_decision[emotion_decision]
    dna_life_engine[life_engine] --> dna_evolution_gene[evolution_gene]
    dna_life_engine[life_engine] --> dna_external_verifier[external_verifier]
    dna_life_engine[life_engine] --> dna_focus_dilution[focus_dilution]
    dna_life_engine[life_engine] --> dna_genome[genome]
    dna_life_engine[life_engine] --> dna_gep_protocol[gep_protocol]
    dna_life_engine[life_engine] --> dna_habit_compiler[habit_compiler]
    dna_life_engine[life_engine] --> dna_life_branch[life_branch]
    dna_life_engine[life_engine] --> dna_life_context[life_context]
    dna_life_stage[life_stage] --> api_token_accountant[token_accountant]
    dna_life_stage[life_stage] --> capability_sub_agent_dispatch[sub_agent_dispatch]
    dna_life_stage[life_stage] --> core_entity_registry[entity_registry]
    dna_life_stage[life_stage] --> core_session_memory[session_memory]
    dna_life_stage[life_stage] --> dna_cone_assembler[cone_assembler]
    dna_life_stage[life_stage] --> dna_expert_role_manager[expert_role_manager]
    dna_life_stage[life_stage] --> dna_inquiry_engine[inquiry_engine]
    dna_life_stage[life_stage] --> dna_latent_reasoner[latent_reasoner]
    dna_life_stage[life_stage] --> dna_life_context[life_context]
    dna_living_world[living_world] --> dna_consciousness[consciousness]
    dna_living_world[living_world] --> dna_genome[genome]
    dna_mental_time_travel[mental_time_travel] --> api_stream_session[stream_session]
    dna_mental_time_travel[mental_time_travel] --> dna_consciousness[consciousness]
    dna_meta_strategy[meta_strategy] --> dna_meta_memory[meta_memory]
    dna_personality[personality] --> dna_adaptive_ui[adaptive_ui]
    dna_personality[personality] --> dna_anticipatory[anticipatory]
    dna_personality[personality] --> dna_biorhythm[biorhythm]
    dna_phenomenal_consciousness[phenomenal_consciousness] --> dna_consciousness_emergence[consciousness_emergence]
    dna_prompt_optimizer[prompt_optimizer] --> dna_model_spec[model_spec]
    dna_safety_coordinator[safety_coordinator] --> dna_immune_system[immune_system]
    dna_self_conditioning[self_conditioning] --> dna_depth_attention[depth_attention]
    dna_self_conditioning[self_conditioning] --> dna_life_context[life_context]
    dna_self_evolution[self_evolution] --> dna_external_learner[external_learner]
    dna_self_evolving[self_evolving] --> core_atomic_modification[atomic_modification]
    dna_self_evolving[self_evolving] --> dna_meta_memory[meta_memory]
    dna_self_evolving[self_evolving] --> dna_meta_strategy[meta_strategy]
    dna_unified_skill_system[unified_skill_system] --> capability_skill_discovery[skill_discovery]
    dna_unified_skill_system[unified_skill_system] --> capability_tool_market[tool_market]
    dna_unified_skill_system[unified_skill_system] --> capability_tool_registry[tool_registry]
    dna_unified_skill_system[unified_skill_system] --> core_async_disk[async_disk]
    dna_unified_skill_system[unified_skill_system] --> dna_meta_memory[meta_memory]
    dna_unified_skill_system[unified_skill_system] --> dna_skill_graph[skill_graph]
    dna_unified_skill_system[unified_skill_system] --> dna_skill_self_learn[skill_self_learn]
    economy___init__[__init__] --> economy_economic_engine[economic_engine]
    economy_thermo_budget[thermo_budget] --> economy_metabolism[metabolism]
    execution___init__[__init__] --> execution_batch_executor[batch_executor]
    execution___init__[__init__] --> execution_checkpoint[checkpoint]
    execution___init__[__init__] --> execution_continuation[continuation]
    execution___init__[__init__] --> execution_cost_aware[cost_aware]
    execution___init__[__init__] --> execution_dag_executor[dag_executor]
    execution___init__[__init__] --> execution_diffusion_planner[diffusion_planner]
    execution___init__[__init__] --> execution_fitness_landscape[fitness_landscape]
    execution___init__[__init__] --> execution_hitl[hitl]
    execution___init__[__init__] --> execution_orchestrator[orchestrator]
    execution___init__[__init__] --> execution_plan_validator[plan_validator]
    execution___init__[__init__] --> execution_quality_checker[quality_checker]
    execution___init__[__init__] --> execution_react_executor[react_executor]
    execution___init__[__init__] --> execution_real_pipeline[real_pipeline]
    execution___init__[__init__] --> execution_rlm[rlm]
    execution___init__[__init__] --> execution_self_healer[self_healer]
    execution___init__[__init__] --> execution_session_manager[session_manager]
    execution___init__[__init__] --> execution_side_git[side_git]
    execution___init__[__init__] --> execution_sub_agent_roles[sub_agent_roles]
    execution___init__[__init__] --> execution_task_planner[task_planner]
    execution___init__[__init__] --> execution_thinking_evolution[thinking_evolution]
    execution_auto_skill_resolver[auto_skill_resolver] --> capability_unified_search[unified_search]
    execution_checkpoint[checkpoint] --> core_task_guard[task_guard]
    execution_context_fold[context_fold] --> dna_output_compressor[output_compressor]
    execution_context_fold[context_fold] --> execution_context_codex[context_codex]
    execution_cron_scheduler[cron_scheduler] --> core_async_disk[async_disk]
    execution_dag_executor[dag_executor] --> execution_context_fold[context_fold]
    execution_quality_checker[quality_checker] --> dna_safety[safety]
    execution_react_executor[react_executor] --> capability_knowledge_forager[knowledge_forager]
    execution_react_executor[react_executor] --> capability_sub_agent_dispatch[sub_agent_dispatch]
    execution_react_executor[react_executor] --> capability_tool_executor[tool_executor]
    execution_react_executor[react_executor] --> capability_unified_file_tool[unified_file_tool]
    execution_react_executor[react_executor] --> capability_unified_search[unified_search]
    execution_react_executor[react_executor] --> capability_web_reach[web_reach]
    execution_react_executor[react_executor] --> capability_world_explorer[world_explorer]
    execution_react_executor[react_executor] --> core_async_disk[async_disk]
    execution_react_executor[react_executor] --> core_chrome_mcp[chrome_mcp]
    execution_react_executor[react_executor] --> core_city_mcp[city_mcp]
    execution_react_executor[react_executor] --> core_session_memory[session_memory]
    execution_react_executor[react_executor] --> core_shell_env[shell_env]
    execution_react_executor[react_executor] --> core_skill_hub[skill_hub]
    execution_react_executor[react_executor] --> dna_evolution[evolution]
    execution_react_executor[react_executor] --> dna_evolution_store[evolution_store]
    execution_react_executor[react_executor] --> dna_expert_role_manager[expert_role_manager]
    execution_react_executor[react_executor] --> dna_multi_agent_debate[multi_agent_debate]
    execution_react_executor[react_executor] --> dna_orthogonality_guard[orthogonality_guard]
    execution_real_pipeline[real_pipeline] --> capability_unified_search[unified_search]
    execution_real_pipeline[real_pipeline] --> capability_web_reach[web_reach]
    execution_real_pipeline[real_pipeline] --> core_task_guard[task_guard]
    execution_real_pipeline[real_pipeline] --> execution_auto_skill_resolver[auto_skill_resolver]
    execution_rlm[rlm] --> execution_context_fold[context_fold]
    execution_self_healer[self_healer] --> cell_regen[regen]
    execution_terminal_compressor[terminal_compressor] --> execution_global_rule_pool[global_rule_pool]
    execution_thinking_evolution[thinking_evolution] --> dna_meta_memory[meta_memory]
    execution_thinking_evolution[thinking_evolution] --> execution_quality_scorer[quality_scorer]
    execution_thinking_evolution[thinking_evolution] --> execution_rank_monitor[rank_monitor]
    execution_tool_router[tool_router] --> execution_context_fold[context_fold]
    execution_treeflow_planner[treeflow_planner] --> execution_gtsm_planner[gtsm_planner]
    execution_unified_pipeline[unified_pipeline] --> core_behavior_tree[behavior_tree]
    execution_unified_pipeline[unified_pipeline] --> execution_dag_executor[dag_executor]
    execution_unified_pipeline[unified_pipeline] --> execution_gtsm_planner[gtsm_planner]
    execution_unified_pipeline[unified_pipeline] --> execution_react_executor[react_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_compaction_executor[compaction_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_discard_executor[discard_executor]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_disco_gc[disco_gc]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_gc_scheduler[gc_scheduler]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_bridge[storage_bridge]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_config[storage_config]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage___init__[__init__] --> infrastructure_storage_trace_collector[trace_collector]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_faiss_backend[faiss_backend]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_memory_backend[memory_backend]
    infrastructure_storage_backends___init__[__init__] --> infrastructure_storage_backends_sqlite_backend[sqlite_backend]
    infrastructure_storage_backends_faiss_backend[faiss_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_faiss_backend[faiss_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_backends_memory_backend[memory_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_memory_backend[memory_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_backends_sqlite_backend[sqlite_backend] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_backends_sqlite_backend[sqlite_backend] --> infrastructure_storage_storage_layer[storage_layer]
    infrastructure_storage_disco_gc[disco_gc] --> infrastructure_storage_compaction_executor[compaction_executor]
    infrastructure_storage_disco_gc[disco_gc] --> infrastructure_storage_discard_executor[discard_executor]
    infrastructure_storage_gc_scheduler[gc_scheduler] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_storage_bridge[storage_bridge] --> infrastructure_storage_disco_gc[disco_gc]
    infrastructure_storage_storage_layer[storage_layer] --> infrastructure_storage_gc_metrics[gc_metrics]
    infrastructure_storage_trace_collector[trace_collector] --> infrastructure_storage_gc_metrics[gc_metrics]
    integration___init__[__init__] --> integration_hub[hub]
    integration___init__[__init__] --> integration_launcher[launcher]
    integration___init__[__init__] --> integration_message_gateway[message_gateway]
    integration___init__[__init__] --> integration_self_updater[self_updater]
    integration___init__[__init__] --> integration_sms_gateway[sms_gateway]
    integration___init__[__init__] --> integration_sse_server[sse_server]
    integration___init__[__init__] --> integration_unified_notifier[unified_notifier]
    integration___init__[__init__] --> integration_wechat_notifier[wechat_notifier]
    integration_hub[hub] --> capability_adaptive_practice[adaptive_practice]
    integration_hub[hub] --> capability_agent_marketplace[agent_marketplace]
    integration_hub[hub] --> capability_code_engine[code_engine]
    integration_hub[hub] --> capability_data_lineage[data_lineage]
    integration_hub[hub] --> capability_extraction_engine[extraction_engine]
    integration_hub[hub] --> capability_idle_consolidator[idle_consolidator]
    integration_hub[hub] --> capability_memory_pipeline[memory_pipeline]
    integration_hub[hub] --> capability_multimodal_parser[multimodal_parser]
    integration_hub[hub] --> capability_network_brain[network_brain]
    integration_hub[hub] --> capability_overnight_task[overnight_task]
    integration_hub[hub] --> capability_pipeline_engine[pipeline_engine]
    integration_hub[hub] --> capability_progressive_trust[progressive_trust]
    integration_hub[hub] --> capability_remote_assist[remote_assist]
    integration_hub[hub] --> capability_self_discovery[self_discovery]
    integration_hub[hub] --> capability_session_continuity[session_continuity]
    integration_hub[hub] --> capability_skill_buckets[skill_buckets]
    integration_hub[hub] --> capability_skill_discovery[skill_discovery]
    integration_hub[hub] --> capability_spark_search[spark_search]
    integration_hub[hub] --> capability_tool_market[tool_market]
    integration_hub[hub] --> capability_web_reach[web_reach]
    integration_hub[hub] --> config_project_scaffold[project_scaffold]
    integration_hub[hub] --> config_secrets[secrets]
    integration_hub[hub] --> core_async_disk[async_disk]
    integration_hub[hub] --> core_autonomous_growth[autonomous_growth]
    integration_hub[hub] --> core_capability_scanner[capability_scanner]
    integration_hub[hub] --> core_concurrency_guard[concurrency_guard]
    integration_hub[hub] --> core_entity_registry[entity_registry]
    integration_hub[hub] --> core_memory_optimizer[memory_optimizer]
    integration_hub[hub] --> core_perf_accel[perf_accel]
    integration_hub[hub] --> core_resilience_brain[resilience_brain]
    integration_hub[hub] --> core_shell_env[shell_env]
    integration_hub[hub] --> core_task_guard[task_guard]
    integration_hub[hub] --> dna_adaptive_ui[adaptive_ui]
    integration_hub[hub] --> dna_agent_roles[agent_roles]
    integration_hub[hub] --> dna_anticipatory[anticipatory]
    integration_hub[hub] --> dna_autonomous_learner[autonomous_learner]
    integration_hub[hub] --> dna_biorhythm[biorhythm]
    integration_hub[hub] --> dna_cache_optimizer[cache_optimizer]
    integration_hub[hub] --> dna_conversation_dna[conversation_dna]
    integration_hub[hub] --> dna_dual_consciousness[dual_consciousness]
    integration_hub[hub] --> dna_evolution[evolution]
    integration_hub[hub] --> dna_evolution_store[evolution_store]
    integration_hub[hub] --> dna_hitl[hitl]
    integration_hub[hub] --> dna_hormone_signaling[hormone_signaling]
    integration_hub[hub] --> dna_immune_system[immune_system]
    integration_hub[hub] --> dna_life_daemon[life_daemon]
    integration_hub[hub] --> dna_multi_agent_debate[multi_agent_debate]
    integration_hub[hub] --> dna_phenomenal_consciousness[phenomenal_consciousness]
    integration_hub[hub] --> dna_predictive_world[predictive_world]
    integration_hub[hub] --> dna_self_narrative[self_narrative]
    integration_hub[hub] --> dna_session_persistence[session_persistence]
    integration_hub[hub] --> dna_skill_progression[skill_progression]
    integration_hub[hub] --> dna_swarm_evolution[swarm_evolution]
    integration_hub[hub] --> economy_economic_engine[economic_engine]
    integration_hub[hub] --> economy_metabolism[metabolism]
    integration_hub[hub] --> execution_batch_executor[batch_executor]
    integration_hub[hub] --> execution_cron_scheduler[cron_scheduler]
    integration_hub[hub] --> execution_react_executor[react_executor]
    integration_hub[hub] --> execution_real_pipeline[real_pipeline]
    integration_hub[hub] --> execution_rlm[rlm]
    integration_hub[hub] --> execution_session_manager[session_manager]
    integration_hub[hub] --> execution_side_git[side_git]
    integration_hub[hub] --> execution_sub_agent_roles[sub_agent_roles]
    integration_launcher[launcher] --> api_server[server]
    integration_launcher[launcher] --> cell_cell_ai[cell_ai]
    integration_launcher[launcher] --> integration_hub[hub]
    integration_self_updater[self_updater] --> integration_pkg_manager[pkg_manager]
    knowledge___init__[__init__] --> knowledge_agentic_rag[agentic_rag]
    knowledge___init__[__init__] --> knowledge_cognitive_delta[cognitive_delta]
    knowledge___init__[__init__] --> knowledge_content_quality[content_quality]
    knowledge___init__[__init__] --> knowledge_context_glossary[context_glossary]
    knowledge___init__[__init__] --> knowledge_context_wiki[context_wiki]
    knowledge___init__[__init__] --> knowledge_document_tree[document_tree]
    knowledge___init__[__init__] --> knowledge_engram_store[engram_store]
    knowledge___init__[__init__] --> knowledge_format_discovery[format_discovery]
    knowledge___init__[__init__] --> knowledge_gap_detector[gap_detector]
    knowledge___init__[__init__] --> knowledge_hallucination_guard[hallucination_guard]
    knowledge___init__[__init__] --> knowledge_hierarchical_chunker[hierarchical_chunker]
    knowledge___init__[__init__] --> knowledge_ideablock_enricher[ideablock_enricher]
    knowledge___init__[__init__] --> knowledge_intelligent_kb[intelligent_kb]
    knowledge___init__[__init__] --> knowledge_knowledge_base[knowledge_base]
    knowledge___init__[__init__] --> knowledge_knowledge_graph[knowledge_graph]
    knowledge___init__[__init__] --> knowledge_knowledge_router[knowledge_router]
    knowledge___init__[__init__] --> knowledge_layout_analyzer[layout_analyzer]
    knowledge___init__[__init__] --> knowledge_learning_engine[learning_engine]
    knowledge___init__[__init__] --> knowledge_learning_sources[learning_sources]
    knowledge___init__[__init__] --> knowledge_modern_ocr[modern_ocr]
    knowledge___init__[__init__] --> knowledge_multidoc_fusion[multidoc_fusion]
    knowledge___init__[__init__] --> knowledge_onto_bridge[onto_bridge]
    knowledge___init__[__init__] --> knowledge_pii_redactor[pii_redactor]
    knowledge___init__[__init__] --> knowledge_provenance[provenance]
    knowledge___init__[__init__] --> knowledge_quality_guard[quality_guard]
    knowledge___init__[__init__] --> knowledge_query_decomposer[query_decomposer]
    knowledge___init__[__init__] --> knowledge_relation_engine[relation_engine]
    knowledge___init__[__init__] --> knowledge_reranker[reranker]
    knowledge___init__[__init__] --> knowledge_retrieval_validator[retrieval_validator]
    knowledge___init__[__init__] --> knowledge_struct_mem[struct_mem]
    knowledge___init__[__init__] --> knowledge_vector_store[vector_store]
    knowledge_engram_store[engram_store] --> execution_context_codex[context_codex]
    knowledge_entity_bridge[entity_bridge] --> knowledge_context_glossary[context_glossary]
    knowledge_hierarchical_chunker[hierarchical_chunker] --> knowledge_document_tree[document_tree]
    knowledge_hypergraph_store[hypergraph_store] --> core_synaptic_plasticity[synaptic_plasticity]
    knowledge_intelligent_kb[intelligent_kb] --> capability_unified_search[unified_search]
    knowledge_intelligent_kb[intelligent_kb] --> capability_web_reach[web_reach]
    knowledge_intelligent_kb[intelligent_kb] --> core_async_disk[async_disk]
    knowledge_intelligent_kb[intelligent_kb] --> dna_selfplay_skill[selfplay_skill]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_document_kb[document_kb]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_engram_store[engram_store]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_fdac_compressor[fdac_compressor]
    knowledge_intelligent_kb[intelligent_kb] --> knowledge_hallucination_guard[hallucination_guard]
    knowledge_knowledge_base[knowledge_base] --> knowledge_dedup[dedup]
    knowledge_knowledge_base[knowledge_base] --> knowledge_engram_store[engram_store]
    knowledge_layout_analyzer[layout_analyzer] --> knowledge_document_tree[document_tree]
    knowledge_lazy_index[lazy_index] --> knowledge_file_chunk_reader[file_chunk_reader]
    knowledge_learning_engine[learning_engine] --> knowledge_knowledge_base[knowledge_base]
    knowledge_multidoc_fusion[multidoc_fusion] --> knowledge_document_tree[document_tree]
    knowledge_multidoc_fusion[multidoc_fusion] --> knowledge_hierarchical_chunker[hierarchical_chunker]
    knowledge_vector_store[vector_store] --> infrastructure_io_optimizer[io_optimizer]
    lsp___init__[__init__] --> lsp_lsp_manager[lsp_manager]
    market___init__[__init__] --> market_opportunity_scorer[opportunity_scorer]
    market___init__[__init__] --> market_revenue_engine[revenue_engine]
    market___init__[__init__] --> market_user_profile[user_profile]
    mcp___init__[__init__] --> mcp_server[server]
    mcp_server[server] --> capability_code_graph[code_graph]
    mcp_server[server] --> capability_tabular_reasoner[tabular_reasoner]
    mcp_server[server] --> capability_tianditu[tianditu]
    mcp_server[server] --> integration_hub[hub]
    mcp_server[server] --> knowledge_engram_store[engram_store]
    mcp_server[server] --> knowledge_pii_redactor[pii_redactor]
    memory___init__[__init__] --> memory_emotional_memory[emotional_memory]
    memory___init__[__init__] --> memory_memory_policy[memory_policy]
    memory___init__[__init__] --> memory_user_model[user_model]
    memory_memory_orchestrator[memory_orchestrator] --> dna_surprise_gating[surprise_gating]
    memory_memory_orchestrator[memory_orchestrator] --> memory_emotional_memory[emotional_memory]
    memory_user_model[user_model] --> execution_context_codex[context_codex]
    memory_user_model[user_model] --> memory_persona_memory[persona_memory]
    network___init__[__init__] --> network_biometric_signature[biometric_signature]
    network___init__[__init__] --> network_config_sync[config_sync]
    network___init__[__init__] --> network_discovery[discovery]
    network___init__[__init__] --> network_distributed_consciousness[distributed_consciousness]
    network___init__[__init__] --> network_domain_ip_pool[domain_ip_pool]
    network___init__[__init__] --> network_encrypted_channel[encrypted_channel]
    network___init__[__init__] --> network_nat_traverse[nat_traverse]
    network___init__[__init__] --> network_node[node]
    network___init__[__init__] --> network_offline_mode[offline_mode]
    network___init__[__init__] --> network_p2p_node[p2p_node]
    network___init__[__init__] --> network_p2p_presence[p2p_presence]
    network___init__[__init__] --> network_presence_sensor[presence_sensor]
    network___init__[__init__] --> network_relay_registry[relay_registry]
    network___init__[__init__] --> network_reputation[reputation]
    network___init__[__init__] --> network_scinet_bandit[scinet_bandit]
    network___init__[__init__] --> network_scinet_cache[scinet_cache]
    network___init__[__init__] --> network_scinet_engine[scinet_engine]
    network___init__[__init__] --> network_scinet_federated[scinet_federated]
    network___init__[__init__] --> network_scinet_hardening[scinet_hardening]
    network___init__[__init__] --> network_scinet_quic[scinet_quic]
    network___init__[__init__] --> network_scinet_service[scinet_service]
    network___init__[__init__] --> network_scinet_swarm[scinet_swarm]
    network___init__[__init__] --> network_scinet_topology[scinet_topology]
    network___init__[__init__] --> network_scinet_vllm[scinet_vllm]
    network___init__[__init__] --> network_scinet_webtransport[scinet_webtransport]
    network___init__[__init__] --> network_site_accelerator[site_accelerator]
    network___init__[__init__] --> network_spatial_awareness[spatial_awareness]
    network_distributed_consciousness[distributed_consciousness] --> dna_consciousness_emergence[consciousness_emergence]
    network_distributed_consciousness[distributed_consciousness] --> dna_swarm_evolution[swarm_evolution]
    network_offline_mode[offline_mode] --> knowledge_knowledge_base[knowledge_base]
    network_p2p_node[p2p_node] --> core_unified_registry[unified_registry]
    network_p2p_node[p2p_node] --> dna_swarm_evolution[swarm_evolution]
    network_p2p_presence[p2p_presence] --> network_collective[collective]
    network_resilience[resilience] --> network_proxy_fetcher[proxy_fetcher]
    network_scinet_engine[scinet_engine] --> network_scinet_bandit[scinet_bandit]
    network_scinet_engine[scinet_engine] --> network_scinet_cache[scinet_cache]
    network_scinet_hardening[scinet_hardening] --> network_proxy_fetcher[proxy_fetcher]
    network_scinet_service[scinet_service] --> network_domain_ip_pool[domain_ip_pool]
    network_scinet_service[scinet_service] --> network_proxy_fetcher[proxy_fetcher]
    network_scinet_service[scinet_service] --> network_scinet_engine[scinet_engine]
    network_scinet_service[scinet_service] --> network_scinet_hardening[scinet_hardening]
    network_site_accelerator[site_accelerator] --> network_domain_ip_pool[domain_ip_pool]
    network_smart_dns[smart_dns] --> network_domain_ip_pool[domain_ip_pool]
    network_smart_dns[smart_dns] --> network_scinet_service[scinet_service]
    network_swarm_coordinator[swarm_coordinator] --> network_message_bus[message_bus]
    network_universal_pairing[universal_pairing] --> network_discovery[discovery]
    network_webrtc_remote[webrtc_remote] --> core_shell_env[shell_env]
    observability___init__[__init__] --> observability_activity_feed[activity_feed]
    observability___init__[__init__] --> observability_agent_eval[agent_eval]
    observability___init__[__init__] --> observability_audit_log[audit_log]
    observability___init__[__init__] --> observability_calibration[calibration]
    observability___init__[__init__] --> observability_change_manifest[change_manifest]
    observability___init__[__init__] --> observability_claim_checker[claim_checker]
    observability___init__[__init__] --> observability_error_replay[error_replay]
    observability___init__[__init__] --> observability_harness_registry[harness_registry]
    observability___init__[__init__] --> observability_logger[logger]
    observability___init__[__init__] --> observability_metrics[metrics]
    observability___init__[__init__] --> observability_sentinel[sentinel]
    observability___init__[__init__] --> observability_setup[setup]
    observability___init__[__init__] --> observability_tracer[tracer]
    observability___init__[__init__] --> observability_trust_scoring[trust_scoring]
    observability_error_replay[error_replay] --> capability_self_modifier[self_modifier]
    observability_setup[setup] --> observability_logger[logger]
    observability_setup[setup] --> observability_metrics[metrics]
    observability_tracer[tracer] --> observability_logger[logger]
    observability_trust_scoring[trust_scoring] --> observability_agent_eval[agent_eval]
    optimization_discovery_machine[discovery_machine] --> optimization_annealing_core[annealing_core]
    reasoning_dialectical___init__[__init__] --> reasoning_dialectical_contradiction_tracker[contradiction_tracker]
    reasoning_dialectical___init__[__init__] --> reasoning_dialectical_phase_transition[phase_transition]
    reasoning_formal___init__[__init__] --> reasoning_formal_rule_engine[rule_engine]
    reasoning_formal___init__[__init__] --> reasoning_formal_syllogism[syllogism]
    reasoning_historical___init__[__init__] --> reasoning_historical_attribution_loop[attribution_loop]
    reasoning_historical___init__[__init__] --> reasoning_historical_consensus_measure[consensus_measure]
    reasoning_historical___init__[__init__] --> reasoning_historical_layering_tracker[layering_tracker]
    reasoning_mathematical___init__[__init__] --> reasoning_mathematical_bayesian_reasoner[bayesian_reasoner]
    reasoning_mathematical___init__[__init__] --> reasoning_mathematical_knowledge_representation[knowledge_representation]
    serialization___init__[__init__] --> serialization_benchmark[benchmark]
    serialization___init__[__init__] --> serialization_protobuf_engine[protobuf_engine]
    serialization___init__[__init__] --> serialization_service_stubs[service_stubs]
    serialization_service_stubs[service_stubs] --> serialization_protobuf_engine[protobuf_engine]
    treellm___init__[__init__] --> treellm_adversarial_selfplay[adversarial_selfplay]
    treellm___init__[__init__] --> treellm_classifier[classifier]
    treellm___init__[__init__] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm___init__[__init__] --> treellm_concurrent_stream[concurrent_stream]
    treellm___init__[__init__] --> treellm_core[core]
    treellm___init__[__init__] --> treellm_deep_probe[deep_probe]
    treellm___init__[__init__] --> treellm_depth_grading[depth_grading]
    treellm___init__[__init__] --> treellm_embedding_scorer[embedding_scorer]
    treellm___init__[__init__] --> treellm_fluid_collective[fluid_collective]
    treellm___init__[__init__] --> treellm_foresight_gate[foresight_gate]
    treellm___init__[__init__] --> treellm_holistic_election[holistic_election]
    treellm___init__[__init__] --> treellm_joint_evolution[joint_evolution]
    treellm___init__[__init__] --> treellm_micro_turn_aware[micro_turn_aware]
    treellm___init__[__init__] --> treellm_onto_prompt_builder[onto_prompt_builder]
    treellm___init__[__init__] --> treellm_proactive_interject[proactive_interject]
    treellm___init__[__init__] --> treellm_prompt_versioning[prompt_versioning]
    treellm___init__[__init__] --> treellm_providers[providers]
    treellm___init__[__init__] --> treellm_reasoning_budget[reasoning_budget]
    treellm___init__[__init__] --> treellm_reasoning_dependency_graph[reasoning_dependency_graph]
    treellm___init__[__init__] --> treellm_route_learner[route_learner]
    treellm___init__[__init__] --> treellm_strategic_orchestrator[strategic_orchestrator]
    treellm___init__[__init__] --> treellm_synapse_aggregator[synapse_aggregator]
    treellm___init__[__init__] --> treellm_vital_signs[vital_signs]
    treellm_adversarial_red_team[adversarial_red_team] --> core_prompt_shield[prompt_shield]
    treellm_adversarial_red_team[adversarial_red_team] --> dna_immune_system[immune_system]
    treellm_adversarial_red_team[adversarial_red_team] --> dna_safety[safety]
    treellm_api_map[api_map] --> capability_public_apis_resource[public_apis_resource]
    treellm_bandit_router[bandit_router] --> core_synaptic_plasticity[synaptic_plasticity]
    treellm_cache_director[cache_director] --> dna_cache_optimizer[cache_optimizer]
    treellm_capability_bus[capability_bus] --> capability_skill_factory[skill_factory]
    treellm_capability_bus[capability_bus] --> capability_tool_market[tool_market]
    treellm_capability_bus[capability_bus] --> dna_unified_skill_system[unified_skill_system]
    treellm_capability_bus[capability_bus] --> execution_react_executor[react_executor]
    treellm_capability_bus[capability_bus] --> mcp_server[server]
    treellm_capability_bus[capability_bus] --> memory_user_model[user_model]
    treellm_classifier[classifier] --> capability_tool_registry[tool_registry]
    treellm_classifier[classifier] --> core_async_disk[async_disk]
    treellm_classifier[classifier] --> dna_skill_graph[skill_graph]
    treellm_cli_anything[cli_anything] --> core_shell_env[shell_env]
    treellm_cli_anything[cli_anything] --> treellm_capability_bus[capability_bus]
    treellm_cli_introspector[cli_introspector] --> core_shell_env[shell_env]
    treellm_cli_introspector[cli_introspector] --> treellm_capability_bus[capability_bus]
    treellm_competitive_eliminator[competitive_eliminator] --> core_async_disk[async_disk]
    treellm_continuous_benchmark[continuous_benchmark] --> treellm_canary_tester[canary_tester]
    treellm_conversation_state_machine[conversation_state_machine] --> knowledge_struct_mem[struct_mem]
    treellm_conversation_state_machine[conversation_state_machine] --> memory_emotional_memory[emotional_memory]
    treellm_conversation_state_machine[conversation_state_machine] --> memory_persona_memory[persona_memory]
    treellm_conversation_state_machine[conversation_state_machine] --> memory_user_model[user_model]
    treellm_core[core] --> capability_industrial_doc_engine[industrial_doc_engine]
    treellm_core[core] --> dna_cache_optimizer[cache_optimizer]
    treellm_core[core] --> dna_task_vector_geometry[task_vector_geometry]
    treellm_core[core] --> dna_unified_skill_system[unified_skill_system]
    treellm_core[core] --> execution_react_executor[react_executor]
    treellm_core[core] --> network_p2p_node[p2p_node]
    treellm_core[core] --> observability_activity_feed[activity_feed]
    treellm_core[core] --> observability_trust_scoring[trust_scoring]
    treellm_core[core] --> treellm_auto_prompt[auto_prompt]
    treellm_core[core] --> treellm_cache_director[cache_director]
    treellm_core[core] --> treellm_capability_bus[capability_bus]
    treellm_core[core] --> treellm_classifier[classifier]
    treellm_daemon_doctor[daemon_doctor] --> treellm_budget_router[budget_router]
    treellm_daemon_doctor[daemon_doctor] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm_daemon_doctor[daemon_doctor] --> treellm_context_moe[context_moe]
    treellm_debug_loop[debug_loop] --> core_shell_env[shell_env]
    treellm_debug_loop[debug_loop] --> treellm_core[core]
    treellm_dream_orchestrator[dream_orchestrator] --> dna_dream_engine[dream_engine]
    treellm_dream_orchestrator[dream_orchestrator] --> treellm_canary_tester[canary_tester]
    treellm_dream_orchestrator[dream_orchestrator] --> treellm_context_moe[context_moe]
    treellm_dream_orchestrator[dream_orchestrator] --> treellm_core[core]
    treellm_error_pattern_learner[error_pattern_learner] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm_holistic_election[holistic_election] --> economy_inverse_reward[inverse_reward]
    treellm_holistic_election[holistic_election] --> treellm_adaptive_weights[adaptive_weights]
    treellm_holistic_election[holistic_election] --> treellm_budget_router[budget_router]
    treellm_holistic_election[holistic_election] --> treellm_cache_director[cache_director]
    treellm_holistic_election[holistic_election] --> treellm_circuit_breaker[circuit_breaker]
    treellm_holistic_election[holistic_election] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm_holistic_election[holistic_election] --> treellm_health_predictor[health_predictor]
    treellm_joint_evolution[joint_evolution] --> knowledge_context_wiki[context_wiki]
    treellm_living_scheduler[living_scheduler] --> treellm_living_renderer[living_renderer]
    treellm_local_tool_bus[local_tool_bus] --> capability_code_graph[code_graph]
    treellm_local_tool_bus[local_tool_bus] --> capability_tabular_reasoner[tabular_reasoner]
    treellm_local_tool_bus[local_tool_bus] --> capability_tianditu[tianditu]
    treellm_local_tool_bus[local_tool_bus] --> knowledge_learning_sources[learning_sources]
    treellm_local_tool_bus[local_tool_bus] --> knowledge_pii_redactor[pii_redactor]
    treellm_local_tool_bus[local_tool_bus] --> treellm_api_map[api_map]
    treellm_local_tool_bus[local_tool_bus] --> treellm_cli_anything[cli_anything]
    treellm_local_tool_bus[local_tool_bus] --> treellm_eia_models[eia_models]
    treellm_model_registry[model_registry] --> treellm_models_dev_sync[models_dev_sync]
    treellm_multimodal_pipeline[multimodal_pipeline] --> capability_multimodal_parser[multimodal_parser]
    treellm_multimodal_pipeline[multimodal_pipeline] --> capability_unified_visual_port[unified_visual_port]
    treellm_multimodal_pipeline[multimodal_pipeline] --> core_inline_parser[inline_parser]
    treellm_multimodal_pipeline[multimodal_pipeline] --> core_unified_speech[unified_speech]
    treellm_prompt_engine[prompt_engine] --> treellm_capability_bus[capability_bus]
    treellm_prompt_engine[prompt_engine] --> treellm_data_value_density[data_value_density]
    treellm_providers[providers] --> api_token_accountant[token_accountant]
    treellm_providers[providers] --> treellm_circuit_breaker[circuit_breaker]
    treellm_providers[providers] --> treellm_connection_pool[connection_pool]
    treellm_reasoning_dependency_graph[reasoning_dependency_graph] --> treellm_holistic_election[holistic_election]
    treellm_route_learner[route_learner] --> execution_fitness_landscape[fitness_landscape]
    treellm_route_learner[route_learner] --> treellm_holistic_election[holistic_election]
    treellm_route_learner[route_learner] --> treellm_model_registry[model_registry]
    treellm_route_learner[route_learner] --> treellm_models_dev_sync[models_dev_sync]
    treellm_safety_models[safety_models] --> treellm_eia_models[eia_models]
    treellm_self_improver[self_improver] --> treellm_capability_bus[capability_bus]
    treellm_self_improver[self_improver] --> treellm_core[core]
    treellm_strategic_distiller[strategic_distiller] --> treellm_recording_engine[recording_engine]
    treellm_strategic_orchestrator[strategic_orchestrator] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm_strategic_orchestrator[strategic_orchestrator] --> treellm_core[core]
    treellm_strategic_orchestrator[strategic_orchestrator] --> treellm_fitness_router[fitness_router]
    treellm_strategic_orchestrator[strategic_orchestrator] --> treellm_holistic_election[holistic_election]
    treellm_survival_mode[survival_mode] --> network_offline_mode[offline_mode]
    treellm_survival_mode[survival_mode] --> treellm_budget_router[budget_router]
    treellm_survival_mode[survival_mode] --> treellm_holistic_election[holistic_election]
    treellm_synapse_aggregator[synapse_aggregator] --> treellm_core[core]
    treellm_synapse_aggregator[synapse_aggregator] --> treellm_pale_detector[pale_detector]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_capability_bus[capability_bus]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_context_moe[context_moe]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_core[core]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_living_input_bus[living_input_bus]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_living_renderer[living_renderer]
    treellm_tree_orchestrator[tree_orchestrator] --> treellm_living_store[living_store]
    treellm_unified_exec[unified_exec] --> core_shell_env[shell_env]
    treellm_unified_exec[unified_exec] --> integration_pkg_manager[pkg_manager]
    treellm_vital_signs[vital_signs] --> treellm_adversarial_selfplay[adversarial_selfplay]
    treellm_vital_signs[vital_signs] --> treellm_bandit_router[bandit_router]
    treellm_vital_signs[vital_signs] --> treellm_classifier[classifier]
    treellm_vital_signs[vital_signs] --> treellm_competitive_eliminator[competitive_eliminator]
    treellm_vital_signs[vital_signs] --> treellm_deep_probe[deep_probe]
    treellm_vital_signs[vital_signs] --> treellm_depth_grading[depth_grading]
    treellm_vital_signs[vital_signs] --> treellm_fluid_collective[fluid_collective]
    treellm_vital_signs[vital_signs] --> treellm_holistic_election[holistic_election]
    treellm_vital_signs[vital_signs] --> treellm_joint_evolution[joint_evolution]
    treellm_vital_signs[vital_signs] --> treellm_proactive_interject[proactive_interject]
    treellm_vital_signs[vital_signs] --> treellm_reasoning_budget[reasoning_budget]
    treellm_vital_signs[vital_signs] --> treellm_reasoning_dependency_graph[reasoning_dependency_graph]
    treellm_vital_signs[vital_signs] --> treellm_strategic_orchestrator[strategic_orchestrator]
    treellm_warm_start_accel[warm_start_accel] --> treellm_election_bus[election_bus]