"""
Question Generator - 提问生成器

根据脱敏后的问题和目标平台，自动生成规范的提问内容：
1. StackOverflow: 包含MCVE（最小可复现示例）
2. 知乎: 叙述性、故事化的提问
3. GitHub Issue: Bug模板、功能请求模板
4. CSDN: 技术博客风格
"""

import re
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from datetime import datetime
from enum import Enum

from .question_sanitizer import SanitizedQuestion
from .platform_selector import Platform, QuestionType


class PostTemplate(Enum):
    """帖子模板"""
    STACKOVERFLOW_QUESTION = "stackoverflow_question"
    STACKOVERFLOW_BUG = "stackoverflow_bug"
    ZHIHU_QUESTION = "zhihu_question"
    GITHUB_ISSUE_BUG = "github_issue_bug"
    GITHUB_ISSUE_FEATURE = "github_issue_feature"
    CSDN_ARTICLE = "csdn_article"
    GENERAL = "general"


@dataclass
class GeneratedPost:
    """生成的帖子"""
    platform: Platform
    template: PostTemplate
    title: str
    body: str
    tags: List[str]
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.now)


class QuestionGenerator:
    """
    提问生成器

    根据平台特点和问题内容，生成规范化的提问
    """

    # StackOverflow 问题模板
    STACKOVERFLOW_TEMPLATE = """
## 问题描述

{question}

## 环境信息

- **操作系统**: {os}
- **编程语言/版本**: {language}
- **相关框架/库版本**: {framework}
- **IDE**: {ide}

## 错误信息

```
{error_message}
```

## 相关代码

```python
{code}
```

## 已尝试的解决方法

1. {attempted_solutions}

## 预期结果

{expected_result}

## 实际结果

{actual_result}

---
帖子由 Smart Help System 自动生成
"""

    # GitHub Issue Bug模板
    GITHUB_BUG_TEMPLATE = """
## Bug描述

{bug_description}

## 复现步骤

1. {step1}
2. {step2}
3. {step3}

## 预期行为

{expected_behavior}

## 实际行为

{actual_behavior}

## 环境信息

- OS: {os}
- Version: {version}
- Browser: {browser}

## 日志

```
{logs}
```

## 截图

如果有相关截图，请在此处粘贴。

---
Bug Report generated by Smart Help System
"""

    # GitHub Feature Request模板
    GITHUB_FEATURE_TEMPLATE = """
## 功能描述

{feature_description}

## 使用场景

{use_case}

## 建议的解决方案

{proposed_solution}

## 替代方案

{alternative_solutions}

## 其他

{additional_info}

---
Feature Request generated by Smart Help System
"""

    # 知乎提问模板
    ZHIHU_TEMPLATE = """
# {title}

最近在{context}，遇到了一个问题：

{question}

## 背景

{background}

## 具体情况

{details}

## 我的尝试

{attempts}

有没有遇到过类似情况的朋友？或者有什么思路可以分享一下吗？

---
提问由 Smart Help System 生成
"""

    # CSDN博客模板
    CSDN_TEMPLATE = """
# {title}

## 前言

{intro}

## 问题回顾

{problem}

## 解决方案

{solution}

## 代码实现

```python
{code}
```

## 运行结果

{results}

## 总结

{summary}

---
文章由 Smart Help System 生成
"""

    def __init__(self):
        self.platform_templates: Dict[Platform, PostTemplate] = {
            Platform.STACKOVERFLOW: PostTemplate.STACKOVERFLOW_QUESTION,
            Platform.ZHIHU: PostTemplate.ZHIHU_QUESTION,
            Platform.GITHUB: PostTemplate.GITHUB_ISSUE_BUG,
            Platform.CSDN: PostTemplate.CSDN_ARTICLE,
            Platform.BLOGGER: PostTemplate.CSDN_ARTICLE,
        }

    def generate(
        self,
        sanitized_question: SanitizedQuestion,
        platform: Platform,
        question_type: QuestionType,
        context: Optional[Dict[str, Any]] = None
    ) -> GeneratedPost:
        """
        生成帖子

        Args:
            sanitized_question: 脱敏后的问题
            platform: 目标平台
            question_type: 问题类型
            context: 额外上下文（错误信息、代码、环境等）

        Returns:
            GeneratedPost: 生成的帖子
        """
        context = context or {}

        # 根据平台和问题类型选择模板
        template = self._select_template(platform, question_type)

        # 生成标题
        title = self._generate_title(sanitized_question.sanitized, platform, question_type)

        # 生成正文
        body = self._generate_body(
            template,
            sanitized_question,
            platform,
            question_type,
            context
        )

        # 生成标签
        tags = self._generate_tags(sanitized_question, platform, question_type)

        return GeneratedPost(
            platform=platform,
            template=template,
            title=title,
            body=body,
            tags=tags,
            metadata={
                "original_question": sanitized_question.original,
                "sanitized_question": sanitized_question.sanitized,
                "privacy_level": sanitized_question.privacy_level,
                "question_type": question_type.value,
            }
        )

    def _select_template(
        self,
        platform: Platform,
        question_type: QuestionType
    ) -> PostTemplate:
        """选择帖子模板"""
        if platform == Platform.STACKOVERFLOW:
            if question_type == QuestionType.BUG_REPORT:
                return PostTemplate.STACKOVERFLOW_BUG
            return PostTemplate.STACKOVERFLOW_QUESTION
        elif platform == Platform.GITHUB:
            if question_type == QuestionType.BUG_REPORT:
                return PostTemplate.GITHUB_ISSUE_BUG
            return PostTemplate.GITHUB_ISSUE_FEATURE
        elif platform == Platform.ZHIHU:
            return PostTemplate.ZHIHU_QUESTION
        elif platform in {Platform.CSDN, Platform.BLOGGER}:
            return PostTemplate.CSDN_ARTICLE
        return PostTemplate.GENERAL

    def _generate_title(
        self,
        question: str,
        platform: Platform,
        question_type: QuestionType
    ) -> str:
        """生成标题"""
        # 截取问题核心（去除口语化表达）
        title = re.sub(r'\[.+?\]', '', question)  # 移除脱敏占位符
        title = re.sub(r'急急急+|跪求|在线等|求助|帮忙', '', title)
        title = title.strip()

        # 限制长度
        if platform == Platform.STACKOVERFLOW:
            max_len = 150
        elif platform == Platform.GITHUB:
            max_len = 100
        else:
            max_len = 200

        if len(title) > max_len:
            title = title[:max_len] + "..."

        # 知乎标题添加前缀
        if platform == Platform.ZHIHU:
            prefixes = {
                QuestionType.ERROR_DEBUG: "编程问题：",
                QuestionType.CONCEPT_UNDERSTAND: "概念请教：",
                QuestionType.TOOL_RECOMMEND: "工具推荐：",
                QuestionType.CAREER_ADVICE: "职业发展：",
            }
            prefix = prefixes.get(question_type, "")
            title = prefix + title

        # GitHub Issue 标题格式
        if platform == Platform.GITHUB:
            if question_type == QuestionType.BUG_REPORT:
                title = f"Bug: {title}"
            else:
                title = f"Feature Request: {title}"

        return title

    def _generate_body(
        self,
        template: PostTemplate,
        sanitized_question: SanitizedQuestion,
        platform: Platform,
        question_type: QuestionType,
        context: Dict[str, Any]
    ) -> str:
        """生成正文"""
        question = sanitized_question.sanitized

        if template == PostTemplate.STACKOVERFLOW_QUESTION:
            return self._generate_stackoverflow_question(
                question, platform, question_type, context
            )
        elif template == PostTemplate.GITHUB_ISSUE_BUG:
            return self._generate_github_bug(question, context)
        elif template == PostTemplate.GITHUB_ISSUE_FEATURE:
            return self._generate_github_feature(question, context)
        elif template == PostTemplate.ZHIHU_QUESTION:
            return self._generate_zhihu_question(question, context)
        elif template == PostTemplate.CSDN_ARTICLE:
            return self._generate_csdn_article(question, context)
        else:
            return question

    def _generate_stackoverflow_question(
        self,
        question: str,
        platform: Platform,
        question_type: QuestionType,
        context: Dict[str, Any]
    ) -> str:
        """生成StackOverflow问题"""
        # 提取各部分
        code = context.get('code', '```\n# 你的代码\n```')
        error_msg = context.get('error_message', '无')
        os_info = context.get('os', 'Windows 11')
        language = context.get('language', 'Python 3.11')
        framework = context.get('framework', 'PyQt6')
        ide = context.get('ide', 'VS Code')
        attempts = context.get('attempts', '暂无')
        expected = context.get('expected', '正常工作')
        actual = context.get('actual', '出现错误')

        return f"""## Problem Description

{question}

## Environment

- **OS**: {os_info}
- **Language/Version**: {language}
- **Framework/Library**: {framework}
- **IDE**: {ide}

## Error Message

```
{error_msg}
```

## Code

{code}

## What I've Tried

1. {attempts}

## Expected Result

{expected}

## Actual Result

{actual}

---
*Posted via Smart Help System*"""

    def _generate_github_bug(
        self,
        bug_description: str,
        context: Dict[str, Any]
    ) -> str:
        """生成GitHub Bug报告"""
        steps = context.get('steps', ['执行操作A', '执行操作B', '出现错误'])
        expected = context.get('expected', '正常行为')
        actual = context.get('actual', 'Bug行为')
        os_info = context.get('os', 'Windows 11')
        version = context.get('version', '1.0.0')
        logs = context.get('logs', '无日志')

        return f"""## Bug Description

{bug_description}

## Steps to Reproduce

1. {steps[0] if len(steps) > 0 else '操作1'}
2. {steps[1] if len(steps) > 1 else '操作2'}
3. {steps[2] if len(steps) > 2 else '操作3'}

## Expected Behavior

{expected}

## Actual Behavior

{actual}

## Environment

- OS: {os_info}
- Version: {version}

## Logs

```
{logs}
```

## Screenshots

If applicable, add screenshots here.
"""

    def _generate_github_feature(
        self,
        feature_description: str,
        context: Dict[str, Any]
    ) -> str:
        """生成GitHub功能请求"""
        use_case = context.get('use_case', '使用场景描述')
        proposed = context.get('proposed', '建议的解决方案')
        alternatives = context.get('alternatives', '替代方案')

        return f"""## Feature Description

{feature_description}

## Use Case

{use_case}

## Proposed Solution

{proposed}

## Alternatives Considered

{alternatives}

## Additional Context

Add any other context about the feature request here.
"""

    def _generate_zhihu_question(
        self,
        question: str,
        context: Dict[str, Any]
    ) -> str:
        """生成知乎提问"""
        title = context.get('title', question[:50])
        background = context.get('background', '项目背景')
        details = context.get('details', '详细情况')
        attempts = context.get('attempts', '已尝试方法')

        return f"""# {title}

最近在{background}，遇到了一个问题：

{question}

## 详细情况

{details}

## 我尝试过

{attempts}

有没有遇到过类似情况的朋友？或者有什么思路可以分享一下吗？

---
*提问由 Smart Help System 生成*
"""

    def _generate_csdn_article(
        self,
        question: str,
        context: Dict[str, Any]
    ) -> str:
        """生成CSDN文章"""
        title = context.get('title', question[:50])
        intro = context.get('intro', '记录一个问题及其解决过程')
        solution = context.get('solution', '解决方案')
        code = context.get('code', '```python\n# 代码实现\n```')
        results = context.get('results', '运行结果')
        summary = context.get('summary', '总结')

        return f"""# {title}

## 前言

{intro}

## 问题回顾

{question}

## 解决方案

{solution}

## 代码实现

{code}

## 运行结果

{results}

## 总结

{summary}

---
*文章由 Smart Help System 生成*
"""

    def _generate_tags(
        self,
        sanitized_question: SanitizedQuestion,
        platform: Platform,
        question_type: QuestionType
    ) -> List[str]:
        """生成标签"""
        tags = []

        # 从脱敏问题中提取关键词
        keywords = sanitized_question.sanitized.replace('[', ' ').replace(']', ' ')
        keywords = re.findall(r'[\w\u4e00-\u9fa5]+', keywords)

        # 过滤出可能是标签的词
        tech_terms = {
            'python', 'java', 'javascript', 'typescript', 'c++', 'c#',
            'react', 'vue', 'angular', 'django', 'flask', 'spring',
            'mysql', 'mongodb', 'redis', 'docker', 'kubernetes',
            'linux', 'git', 'github', 'api', 'http', 'tcp', 'udp',
        }

        for kw in keywords:
            if kw.lower() in tech_terms:
                tags.append(kw.lower())

        # 根据平台添加必要标签
        if platform == Platform.STACKOVERFLOW:
            tags.extend(['python', 'debugging'])  # 示例
        elif platform == Platform.GITHUB:
            if question_type == QuestionType.BUG_REPORT:
                tags.extend(['bug'])
            else:
                tags.extend(['enhancement'])

        # 去重
        return list(dict.fromkeys(tags))[:10]

    def estimate_response_time(
        self,
        platform: Platform,
        question_type: QuestionType
    ) -> str:
        """估算响应时间"""
        estimates = {
            Platform.STACKOVERFLOW: {
                QuestionType.ERROR_DEBUG: "10分钟~2小时",
                QuestionType.BUG_REPORT: "1小时~1天",
                QuestionType.CODE_OPTIMIZATION: "1小时~1天",
                QuestionType.GENERAL: "30分钟~4小时",
            },
            Platform.ZHIHU: {
                QuestionType.CONCEPT_UNDERSTAND: "2小时~1天",
                QuestionType.CAREER_ADVICE: "1天~3天",
                QuestionType.TOOL_RECOMMEND: "1天~1周",
                QuestionType.GENERAL: "1天~3天",
            },
            Platform.GITHUB: {
                QuestionType.BUG_REPORT: "1天~1周",
                QuestionType.FRAMEWORK_QUESTION: "3天~2周",
                QuestionType.GENERAL: "1天~1周",
            },
            Platform.CSDN: {
                QuestionType.ERROR_DEBUG: "1小时~1天",
                QuestionType.GENERAL: "1天~1周",
            },
        }

        platform_estimates = estimates.get(platform, {})
        return platform_estimates.get(question_type, "数小时~数天")
