"""
环评智能工作台 (EIA Intelligence Workbench)
==========================================

核心理念：将环评工作流彻底"软件定义"，实现全流程自动化。

模块结构：
- EIAWorkbench: 环评智能工作台主入口
- DocumentParser: 智能资料解读（PDF/Word/图片）
- SourceCalculator: 污染源源强核算
- DrawingEngine: 环评智能绘图（CAD/流程图/防护距离）
- MapOverlay: GIS 地图叠加层
- ReportGenerator: 报告自动组装
- ComplianceChecker: 合规性自检
- P2PKnowledge: P2P 知识共享网络
"""

from .workbench import (
    EIAWorkbench,
    ProjectConfig,
    create_eia_workbench,
)
from .document_parser import (
    DocumentParser,
    ParsedDocument,
    ExtractedData,
    create_document_parser,
)
from .source_calculator import (
    SourceCalculator,
    PollutionSource,
    calculate_source_strength,
)
from .drawing_engine import (
    DrawingEngine,
    DrawingLayer,
    FlowChartNode,
    ProtectionZone,
    create_drawing_engine,
)
from .map_overlay import (
    MapOverlay,
    CoordinateSystem,
    create_map_overlay,
)
from .report_generator import (
    ReportGenerator,
    ReportSection,
    create_report_generator,
)
from .compliance_checker import (
    ComplianceChecker,
    ComplianceItem,
    check_compliance,
)
from .collaborative_generator import (
    CollaborativeReportEngine,
    CollaborativeReportConfig,
    ReportSectionDraft,
    VerificationMarker,
    ConfidenceLevel,
    SectionStatus,
    ContentSource,
    create_collaborative_engine,
)
from .data_consistency_checker import (
    DataConsistencyChecker,
    ConsistencyIssue,
    ConsistencyIssueType,
    ConsistencyLevel,
    create_consistency_checker,
)
from .section_verification import (
    SectionVerificationTracker,
    VerificationTask,
    VerificationRecord,
    VerificationAction,
    create_verification_tracker,
)
from .calculation_engine import (
    ModelCalculationEngine,
    ComputationInput,
    ComputationResult,
    ComputationPackage,
    ModelParameter,
    ModelType,
    ComputationStatus,
    ParameterSource,
    create_calculation_engine,
)
from .result_validator import (
    ResultValidator,
    VerificationReport,
    ComputationHistory,
    VerificationLevel,
    VerificationResult,
    create_result_validator,
)
from .computation_fingerprint import (
    ComputationFingerprintGenerator,
    Fingerprint,
    FingerprintChain,
    FingerprintStatus,
    create_fingerprint_generator,
)
from .export_manager import (
    ExportManager,
    ExportFormat,
    ExportConfig,
    ExportItem,
    VerificationPackage,
    VerificationLevel as ExportVerificationLevel,
    create_export_manager,
    export_for_verification,
    export_eiapro_package,
    export_docker_package,
)
from .verification_feedback import (
    VerificationFeedbackSystem,
    VerificationFeedback,
    DifferenceRecord,
    DifferenceType,
    DifferenceSeverity,
    FeedbackSource,
    LearningRecord,
    create_feedback_system,
    submit_engineer_feedback,
    upload_external_verification,
    compare_and_learn,
)
from .generation_monitor import (
    GenerationMonitor,
    GenerationStage,
    StageStatus,
    StepStatus,
    GenerationStep,
    StageProgress,
    GenerationSnapshot,
    ProgressBroadcaster,
    get_or_create_monitor,
    start_report_generation,
    update_stage,
    update_step,
    complete_report_generation,
    get_generation_state,
)
from .report_completeness_auditor import (
    ReportCompletenessAuditor,
    MissingItem,
    MissingLevel,
    MissingCategory,
    Suggestion,
    AuditResult,
    get_auditor,
    audit_report_completeness,
)

# 空间智能模块
from .spatial_intelligence import (
    POICategory,
    POIPoint,
    SensitiveZone,
    TerrainData,
    SpatialAnalysisResult,
    SpatialIntelligenceEngine,
    get_spatial_engine,
    analyze_project_location,
)

# 环境数据连接器模块
from .environmental_data import (
    DataSource,
    DataQuality,
    AirQualityData,
    WaterQualityData,
    MeteorologicalData,
    EnvironmentalBaselineData,
    CNEMCConnector,
    WeatherAPIConnector,
    WaterQualityConnector,
    EnvironmentalDataHub,
    get_environmental_data_hub,
    get_environmental_baseline,
)

# 气象智能（动态站点匹配 + AERMOD）
from .meteorological_intelligence import (
    # 枚举
    StationType,
    DataStatus,
    ServiceStatus,
    # 模型
    WeatherStation,
    MetDataFile,
    StationIndex,
    MetCacheEntry,
    MetCacheManifest,
    ProjectLocation,
    MatchedStation,
    AERMODInput,
    AERMODConfig,
    EmissionSource,
    DownloadTask,
    # 站点管理
    StationIndexManager,
    get_station_index_manager,
    find_nearest_station,
    # 缓存管理
    MetCacheManager,
    get_met_cache_manager,
    check_met_cache,
    # 最近查找
    NearestStationFinder,
    MatchOptions,
    find_nearest_for_project,
    find_and_prepare_station,
    deg_to_km,
    haversine_distance_km,
    # AERMOD生成
    AERMODInputGenerator,
    generate_aermod_inp,
    create_sample_inp,
    # 服务
    MeteorologicalService,
    MetServiceConfig,
    get_meteorological_service,
    match_nearest,
    generate_inp,
)

# 政策合规与知识库模块
from .policy_knowledge import (
    StandardType,
    StandardLevel,
    Standard,
    StandardClause,
    SimilarProject,
    PermitInfo,
    ComplianceCheckResult,
    StandardsDatabase,
    SimilarProjectsFinder,
    PollutionPermitChecker,
    PolicyKnowledgeEngine,
    get_policy_engine,
)

# 分布式P2P数据网络模块
from .distributed_data import (
    DataCategory,
    P2PDataQuality,
    NodeRole,
    DataPackage,
    ModelParameterPackage,
    NodeInfo,
    DataRequest,
    DataSharingStats,
    DataAnonymizer,
    P2PBaselineNetwork,
    TypicalParametersLibrary,
    get_p2p_network,
    get_param_library,
)

# 智能审查引擎
from .review_engine import (
    # 数字孪生验证
    "DigitalTwinVerifier",
    "PredictionInput",
    "PredictionResult",
    "DistanceVerification",
    "VerificationReport",
    "VerificationStatus",
    "get_verifier",
    "verify_prediction_async",
    "verify_distance_async",
    # 知识图谱合规
    "KnowledgeGraphComplianceEngine",
    "StandardKnowledgeGraph",
    "ComplianceCheckResult",
    "CrossChapterInference",
    "ComplianceReport",
    "ComplianceStatus",
    "get_compliance_engine",
    "check_compliance_async",
    # 智能修复
    "SmartRepairEngine",
    "RepairSuggestion",
    "AutoPatch",
    "RepairVerification",
    "SmartRepairReport",
    "IssueLevel",
    "RepairAction",
    "get_repair_engine",
    "analyze_and_repair_async",
    # 对抗性测试
    "AdversarialTester",
    "UncertaintyResult",
    "ExtremeScenario",
    "MonteCarloResult",
    "TestReport",
    "get_tester",
    "run_adversarial_test_async",
    # 分布式审查
    "DistributedReviewNetwork",
    "ReviewNode",
    "ReviewTask",
    "ReviewVote",
    "ConsensusResult",
    "ConsensusLevel",
    "get_review_network",
    # 主引擎
    "IntelligentReviewEngine",
    "ReviewSession",
    "IntegratedReviewReport",
    "ReviewMode",
    "ReviewStage",
    "get_review_engine",
    "start_review_async",
    "generate_integrated_report",
    # UI面板
    "IntelligentReviewPanel",
    "DigitalTwinVerificationPanel",
    "KnowledgeGraphCompliancePanel",
    "SmartRepairPanel",
    "AdversarialTestPanel",
    "DistributedReviewPanel",
    "ScoreGauge",
    "StatusIndicator",
    "IssueLevelBadge",
)

# 应急预案模块
from .emergency_response import (
    "AccidentType",
    "HazardLevel",
    "HazardousSubstance",
    "AccidentScenario",
    "ResourceGap",
    "EmergencyPlan",
    "EmergencyResponseEngine",
    "get_emergency_engine",
)

# 验收监测模块
from .acceptance_monitoring import (
    "MonitoringType",
    "MonitoringPoint",
    "Monitoring布点Scheme",
    "MeasuredData",
    "EvaluationResult",
    "AcceptanceMonitoringReport",
    "Smart布点Engine",
    "DataValidationEngine",
    "ComplianceEvaluationEngine",
    "AcceptanceMonitoringEngine",
    "get_monitoring_engine",
)

# 排污许可模块
from .pollution_permit import (
    "PermitType",
    "WorkCondition",
    "Pollutant",
    "PollutionSource",
    "PermitApplication",
    "PermitQuantityCalculation",
    "ComplianceCheck",
    "MonitoringReminder",
    "PollutionPermit",
    "EmissionFactorKnowledgeBase",
    "PermitQuantityCalculator",
    "ComplianceChecker",
    "PostPermitManager",
    "PollutionPermitEngine",
    "get_permit_engine",
)

# 数据联动引擎
from .scenario_linkage import (
    "ScenarioType",
    "DataFlowDirection",
    "DataLink",
    "SyncedData",
    "KnowledgeParticle",
    "ModelFeedback",
    "IntegratedLifecycleReport",
    "DataLinkageEngine",
    "get_linkage_engine",
    "generate_lifecycle_async",
)

# 智能表单系统
from .smart_form import (
    # 数据模型
    "DocumentType",
    "ExtractionConfidence",
    "ExtractedField",
    "ValidationResult",
    "ExtractionResult",
    # 文档解析
    "DocumentFormExtractor",
    "AIExtractEngine",
    "KnowledgeBaseValidator",
    "get_extractor",
    "extract_form_data_async",
    # 表单生成
    "WYSIWYGFormGenerator",
    "FieldHTMLGenerator",
    "generate_form_html",
    "generate_minimal_form",
    "get_generator",
    # 动态生成
    "FormCategory",
    "FieldDefinition",
    "FormTemplate",
    "IndustryKnowledgeBase",
    "DynamicFormGenerator",
    "FormValidationEngine",
    "get_dynamic_generator",
    "generate_dynamic_form_async",
    # 数据同步
    "DataSource",
    "FormDataChunk",
    "SyncMetadata",
    "SyncResult",
    "FormDataSynchronizer",
    "FormChangeTracker",
    "get_synchronizer",
    "get_tracker",
    "save_form_data_async",
    "load_form_data_async",
    # 主控制器
    "SmartFormMode",
    "FormStatus",
    "SmartFormSession",
    "SmartFormConfig",
    "SmartFormController",
    "SmartFormAPI",
    "SmartFormWebSocket",
    "get_smart_form_controller",
    "create_form_session",
    "process_uploaded_document",
    "submit_form_data",
)

__all__ = [
    # 主工作台
    "EIAWorkbench",
    "ProjectConfig",
    "create_eia_workbench",
    # 文档解析
    "DocumentParser",
    "ParsedDocument",
    "ExtractedData",
    "create_document_parser",
    # 源强核算
    "SourceCalculator",
    "PollutionSource",
    "calculate_source_strength",
    # 绘图引擎
    "DrawingEngine",
    "DrawingLayer",
    "FlowChartNode",
    "ProtectionZone",
    "create_drawing_engine",
    # 地图叠加
    "MapOverlay",
    "CoordinateSystem",
    "create_map_overlay",
    # 报告生成
    "ReportGenerator",
    "ReportSection",
    "create_report_generator",
    # 合规检查
    "ComplianceChecker",
    "ComplianceItem",
    "check_compliance",
    # 人机协同报告生成
    "CollaborativeReportEngine",
    "CollaborativeReportConfig",
    "ReportSectionDraft",
    "VerificationMarker",
    "ConfidenceLevel",
    "SectionStatus",
    "ContentSource",
    "create_collaborative_engine",
    # 数据一致性检查
    "DataConsistencyChecker",
    "ConsistencyIssue",
    "ConsistencyIssueType",
    "ConsistencyLevel",
    "create_consistency_checker",
    # 章节审核追踪
    "SectionVerificationTracker",
    "VerificationTask",
    "VerificationRecord",
    "VerificationAction",
    "create_verification_tracker",
    # 模型计算引擎
    "ModelCalculationEngine",
    "ComputationInput",
    "ComputationResult",
       "ComputationPackage",
    "ModelParameter",
    "ModelType",
    "ComputationStatus",
    "ParameterSource",
    "create_calculation_engine",
    # 结果验证器
    "ResultValidator",
    "VerificationReport",
    "ComputationHistory",
    "VerificationLevel",
    "VerificationResult",
    "create_result_validator",
    # 计算指纹
    "ComputationFingerprintGenerator",
    "Fingerprint",
    "FingerprintChain",
    "FingerprintStatus",
    "create_fingerprint_generator",
    # 导出管理器
    "ExportManager",
    "ExportFormat",
    "ExportConfig",
    "ExportItem",
    "VerificationPackage",
    "ExportVerificationLevel",
    "create_export_manager",
    "export_for_verification",
    "export_eiapro_package",
    "export_docker_package",
    # 验证反馈系统
    "VerificationFeedbackSystem",
    "VerificationFeedback",
    "DifferenceRecord",
    "DifferenceType",
    "DifferenceSeverity",
    "FeedbackSource",
    "LearningRecord",
    "create_feedback_system",
    "submit_engineer_feedback",
    "upload_external_verification",
    "compare_and_learn",
    # 生成过程监控
    "GenerationMonitor",
    "GenerationStage",
    "StageStatus",
    "StepStatus",
    "GenerationStep",
    "StageProgress",
    "GenerationSnapshot",
    "ProgressBroadcaster",
    "get_or_create_monitor",
    "start_report_generation",
    "update_stage",
    "update_step",
    "complete_report_generation",
    "get_generation_state",
    # 报告完整性审计
    "ReportCompletenessAuditor",
    "MissingItem",
    "MissingLevel",
    "MissingCategory",
    "Suggestion",
    "AuditResult",
    "get_auditor",
    "audit_report_completeness",
    # 空间智能
    "POICategory",
    "POIPoint",
    "SensitiveZone",
    "TerrainData",
    "SpatialAnalysisResult",
    "SpatialIntelligenceEngine",
    "get_spatial_engine",
    "analyze_project_location",
    # 环境数据连接器
    "DataSource",
    "DataQuality",
    "AirQualityData",
    "WaterQualityData",
    "MeteorologicalData",
    "EnvironmentalBaselineData",
    "CNEMCConnector",
    "WeatherAPIConnector",
    "WaterQualityConnector",
    "EnvironmentalDataHub",
    "get_environmental_data_hub",
    "get_environmental_baseline",
    # 气象智能（动态站点匹配 + AERMOD）
    "StationType",
    "DataStatus",
    "ServiceStatus",
    "WeatherStation",
    "MetDataFile",
    "StationIndex",
    "MetCacheEntry",
    "MetCacheManifest",
    "ProjectLocation",
    "MatchedStation",
    "AERMODInput",
    "AERMODConfig",
    "EmissionSource",
    "DownloadTask",
    "StationIndexManager",
    "get_station_index_manager",
    "find_nearest_station",
    "MetCacheManager",
    "get_met_cache_manager",
    "check_met_cache",
    "NearestStationFinder",
    "MatchOptions",
    "find_nearest_for_project",
    "find_and_prepare_station",
    "deg_to_km",
    "haversine_distance_km",
    "AERMODInputGenerator",
    "generate_aermod_inp",
    "create_sample_inp",
    "MeteorologicalService",
    "MetServiceConfig",
    "get_meteorological_service",
    "match_nearest",
    "generate_inp",
    # 政策合规与知识库
    "StandardType",
    "StandardLevel",
    "Standard",
    "StandardClause",
    "SimilarProject",
    "PermitInfo",
    "ComplianceCheckResult",
    "StandardsDatabase",
    "SimilarProjectsFinder",
    "PollutionPermitChecker",
    "PolicyKnowledgeEngine",
    "get_policy_engine",
    # P2P分布式数据网络
    "DataCategory",
    "P2PDataQuality",
    "NodeRole",
    "DataPackage",
    "ModelParameterPackage",
    "NodeInfo",
    "DataRequest",
    "DataSharingStats",
    "DataAnonymizer",
    "P2PBaselineNetwork",
    "TypicalParametersLibrary",
    "get_p2p_network",
    "get_param_library",
    # 数字孪生验证
    "DigitalTwinVerifier",
    "PredictionInput",
    "PredictionResult",
    "DistanceVerification",
    "VerificationReport",
    "VerificationStatus",
    "get_verifier",
    "verify_prediction_async",
    "verify_distance_async",
    # 知识图谱合规
    "KnowledgeGraphComplianceEngine",
    "StandardKnowledgeGraph",
    "ComplianceCheckResult",
    "CrossChapterInference",
    "ComplianceReport",
    "ComplianceStatus",
    "get_compliance_engine",
    "check_compliance_async",
    # 智能修复
    "SmartRepairEngine",
    "RepairSuggestion",
    "AutoPatch",
    "RepairVerification",
    "SmartRepairReport",
    "IssueLevel",
    "RepairAction",
    "get_repair_engine",
    "analyze_and_repair_async",
    # 对抗性测试
    "AdversarialTester",
    "UncertaintyResult",
    "ExtremeScenario",
    "MonteCarloResult",
    "TestReport",
    "get_tester",
    "run_adversarial_test_async",
    # 分布式审查
    "DistributedReviewNetwork",
    "ReviewNode",
    "ReviewTask",
    "ReviewVote",
    "ConsensusResult",
    "ConsensusLevel",
    "get_review_network",
    # 主引擎
    "IntelligentReviewEngine",
    "ReviewSession",
    "IntegratedReviewReport",
    "ReviewMode",
    "ReviewStage",
    "get_review_engine",
    "start_review_async",
    "generate_integrated_report",
    # UI面板
    "IntelligentReviewPanel",
    "DigitalTwinVerificationPanel",
    "KnowledgeGraphCompliancePanel",
    "SmartRepairPanel",
    "AdversarialTestPanel",
    "DistributedReviewPanel",
    "ScoreGauge",
    "StatusIndicator",
    "IssueLevelBadge",
    # 应急预案
    "AccidentType",
    "HazardLevel",
    "HazardousSubstance",
    "AccidentScenario",
    "ResourceGap",
    "EmergencyPlan",
    "EmergencyResponseEngine",
    "get_emergency_engine",
    # 验收监测
    "MonitoringType",
    "MonitoringPoint",
    "Monitoring布点Scheme",
    "MeasuredData",
    "EvaluationResult",
    "AcceptanceMonitoringReport",
    "Smart布点Engine",
    "DataValidationEngine",
    "ComplianceEvaluationEngine",
    "AcceptanceMonitoringEngine",
    "get_monitoring_engine",
    # 排污许可
    "PermitType",
    "WorkCondition",
    "Pollutant",
    "PollutionSource",
    "PermitApplication",
    "PermitQuantityCalculation",
    "ComplianceCheck",
    "MonitoringReminder",
    "PollutionPermit",
    "EmissionFactorKnowledgeBase",
    "PermitQuantityCalculator",
    "ComplianceChecker",
    "PostPermitManager",
    "PollutionPermitEngine",
    "get_permit_engine",
    # 数据联动
    "ScenarioType",
    "DataFlowDirection",
    "DataLink",
    "SyncedData",
    "KnowledgeParticle",
    "ModelFeedback",
    "IntegratedLifecycleReport",
    "DataLinkageEngine",
    "get_linkage_engine",
    "generate_lifecycle_async",
    # 智能表单
    "DocumentType",
    "ExtractionConfidence",
    "ExtractedField",
    "ValidationResult",
    "ExtractionResult",
    "DocumentFormExtractor",
    "AIExtractEngine",
    "KnowledgeBaseValidator",
    "get_extractor",
    "extract_form_data_async",
    "WYSIWYGFormGenerator",
    "FieldHTMLGenerator",
    "generate_form_html",
    "generate_minimal_form",
    "get_generator",
    "FormCategory",
    "FieldDefinition",
    "FormTemplate",
    "IndustryKnowledgeBase",
    "DynamicFormGenerator",
    "FormValidationEngine",
    "get_dynamic_generator",
    "generate_dynamic_form_async",
    "DataSource",
    "FormDataChunk",
    "SyncMetadata",
    "SyncResult",
    "FormDataSynchronizer",
    "FormChangeTracker",
    "get_synchronizer",
    "get_tracker",
    "save_form_data_async",
    "load_form_data_async",
    "SmartFormMode",
    "FormStatus",
    "SmartFormSession",
    "SmartFormConfig",
    "SmartFormController",
    "SmartFormAPI",
    "SmartFormWebSocket",
    "get_smart_form_controller",
    "create_form_session",
    "process_uploaded_document",
    "submit_form_data",
]