"""Knowledge Gravity Model — formal laws of knowledge attraction.

Based on Einstein (1915) field equations + Verlinde (2011) entropic gravity:

  G_μν + Λ g_μν = (8πG/c⁴) T_μν      →  knowledge curvature
  F = T ΔS / Δx                       →  knowledge entropy force

In the knowledge hypergraph:
  - Mass (M) → entity importance (weight × frequency × centrality)
  - Distance (r) → semantic dissimilarity between entities
  - Force (F) → retrieval attraction toward a knowledge region
  - Curvature → query-relevance distortion of the retrieval path

Usage:
    gravity = KnowledgeGravity(hypergraph_store)
    field = gravity.compute_field(seed_entities=query_terms)
    # field acts as a "gravitational lens" that bends retrieval trajectories
    weighted_sequence = gravity.lens_trajectory(trajectory, field)
"""

from __future__ import annotations

import math
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any

from loguru import logger


# ═══ Physical Analog Types ═══


@dataclass
class KnowledgeMass:
    """Knowledge mass of an entity — analogous to gravitational mass.

    M = α·weight × β·frequency × γ·centrality × δ·recency
    """
    entity_id: str
    raw_mass: float = 1.0           # M = combined metrics
    centrality: float = 0.5         # Eigenvector centrality in hypergraph
    frequency: int = 1              # How often accessed/retrieved
    recency: float = 0.0            # Seconds since last access (smaller=more recent)
    last_updated: float = 0.0


@dataclass
class GravityField:
    """Gravitational field generated by a set of knowledge masses.

    Analogous to the metric perturbation h_μν from stress-energy T_μν.
    For each point in knowledge space, the field defines an attraction vector
    toward knowledge-dense regions.
    """
    field_id: str
    seed_entities: list[str]
    masses: dict[str, KnowledgeMass]            # entity_id → mass
    field_strength: dict[str, float]            # entity_id → total force ∝ Σ M_i / r²
    curvature: dict[str, float]                 # entity_id → Ricci-like curvature
    total_entropy: float = 0.0                  # S = -Σ p log p over the field
    dominant_cluster: str = ""                  # ID of the mass-dominant cluster center


@dataclass
class GravityForce:
    """Gravitational force between two knowledge entities.

    F_ij = G × M_i × M_j / r_ij²           (Newtonian analog, Verlinde entropic limit)
    Where r_ij = 1 - cosine_similarity(embedding_i, embedding_j)
    """
    entity_a: str
    entity_b: str
    force_magnitude: float = 0.0   # Positive = attraction
    distance: float = 1.0          # Semantic distance in [0, 1]
    mass_a: float = 1.0
    mass_b: float = 1.0


# ═══ Knowledge Gravity Engine ═══


class KnowledgeGravity:
    """Knowledge Gravity Model — formalizes knowledge attraction in hypergraphs.

    Core physics analog:
      - Einstein field eq: mass-energy tells spacetime how to curve
      - In knowledge space: query tells the hypergraph how to curve retrieval paths
      - Verlinde entropic force: F = T × ΔS / Δx
      - In knowledge space: retrieval direction = entropy gradient toward relevant clusters

    Two usage modes:
      1. compute_field(seed_entities) → get the gravity field around a query
      2. lens_trajectory(trajectory, field) → bend the retrieval path through the field
    """

    # Gravitational constant for knowledge space (empirically tuned)
    G_KNOWLEDGE: float = 6.674e-1   # Scaled for our metric space
    LIGHTSPEED: float = 1.0         # c=1 in natural units — max similarity = 1
    HUBBLE_CONSTANT: float = 0.07   # Cosmological expansion ≈ knowledge decay rate

    def __init__(self, hypergraph_store=None):
        self._hg = hypergraph_store
        self._entity_embeddings: dict[str, list[float]] = {}
        self._access_count: dict[str, int] = defaultdict(int)
        self._last_access: dict[str, float] = {}
        self._field_cache: dict[str, GravityField] = {}

    # ── Mass Computation ──

    def compute_mass(self, entity_id: str) -> KnowledgeMass:
        """Compute the knowledge mass of an entity.

        M = weight × log(1+frequency) × centrality × recency_decay
        """
        if not self._hg:
            return KnowledgeMass(entity_id=entity_id, raw_mass=1.0)

        entity = self._hg.get_entity(entity_id)
        he_weight = 1.0
        if entity_id in self._hg._hyperedges:
            he_weight = self._hg._hyperedges[entity_id].weight

        # Centrality: node degree in hypergraph
        centrality = 0.5
        if entity_id in self._hg._graph:
            degree = self._hg._graph.degree(entity_id)
            max_deg = max(
                (d for _, d in self._hg._graph.degree()), default=1)
            centrality = degree / max(max_deg, 1)

        freq = self._access_count.get(entity_id, 1)

        # Recency decay: e^(-t/τ) where τ = 3600s (1 hour half-life)
        last = self._last_access.get(entity_id, 0.0)
        import time
        age = max(0, time.time() - last)
        recency = math.exp(-age / 3600.0)

        raw_mass = he_weight * math.log(1 + freq) * centrality * (0.3 + 0.7 * recency)

        return KnowledgeMass(
            entity_id=entity_id,
            raw_mass=max(0.01, raw_mass),
            centrality=centrality,
            frequency=freq,
            recency=recency,
            last_updated=last,
        )

    # ── Distance Computation ──

    def _semantic_distance(self, entity_a: str, entity_b: str) -> float:
        """Compute semantic distance between two entities (0=identical, 1=maximally different).

        Uses cosine similarity of stored embeddings, falls back to string similarity.
        """
        emb_a = self._entity_embeddings.get(entity_a)
        emb_b = self._entity_embeddings.get(entity_b)

        if emb_a and emb_b and len(emb_a) == len(emb_b):
            dot = sum(x * y for x, y in zip(emb_a, emb_b))
            na = math.sqrt(sum(x * x for x in emb_a))
            nb = math.sqrt(sum(y * y for y in emb_b))
            if na > 0 and nb > 0:
                sim = max(0.0, min(1.0, dot / (na * nb)))
                return 1.0 - sim

        # Fallback: label similarity via Jaccard on character 3-grams
        label_a = entity_a.lower()
        label_b = entity_b.lower()
        if label_a == label_b:
            return 0.0
        n = 3
        grams_a = {label_a[i:i+n] for i in range(max(0, len(label_a) - n + 1))}
        grams_b = {label_b[i:i+n] for i in range(max(0, len(label_b) - n + 1))}
        if not grams_a or not grams_b:
            return 1.0
        inter = len(grams_a & grams_b)
        union = len(grams_a | grams_b)
        sim = inter / union if union else 0
        return 1.0 - sim

    # ── Field Computation ──

    def compute_field(
        self,
        seed_entities: list[str],
        radius: float = 3.0,            # Max graph hops to expand
        max_entities: int = 100,
    ) -> GravityField:
        """Compute the knowledge gravity field around seed entities.

        Algorithm (Einstein Field analog):
          1. Seed → find all entities within radius hops via hypergraph BFS
          2. Compute mass M_i for each entity
          3. Compute forces F_ij between all pairs → curvature R_i = Σ_j F_ij
          4. Sort by curvature, return field

        Args:
            seed_entities: Starting entities (query decomposition)
            radius: Max hypergraph expansion radius (hops)
            max_entities: Cap on entities in the field

        Returns:
            GravityField with masses, field_strength, curvature, entropy
        """
        import time
        field_id = f"gf_{time.time():.0f}_{seed_entities[0][:8] if seed_entities else 'empty'}"

        if not self._hg or not seed_entities:
            return GravityField(
                field_id=field_id, seed_entities=seed_entities,
                masses={}, field_strength={}, curvature={},
            )

        # BFS expansion from seeds
        frontier = set(seed_entities)
        visited: set[str] = set()
        expansion: dict[str, int] = {}  # entity → hop distance from nearest seed

        for i in range(int(radius) + 1):
            next_frontier = set()
            for entity_id in frontier:
                if entity_id in visited:
                    continue
                visited.add(entity_id)
                expansion[entity_id] = i
                # Expand to neighbors (entities sharing hyperedges)
                if entity_id in self._hg._graph:
                    for neighbor in self._hg._graph.neighbors(entity_id):
                        node_data = self._hg._graph.nodes[neighbor]
                        # Only follow to entity nodes (not hyperedge nodes)
                        if node_data.get("type") == "entity" and neighbor not in visited:
                            next_frontier.add(neighbor)
            frontier = next_frontier
            if len(visited) >= max_entities:
                break

        # Compute masses
        masses: dict[str, KnowledgeMass] = {}
        for eid in visited:
            masses[eid] = self.compute_mass(eid)
            if not masses[eid].raw_mass:
                masses[eid].raw_mass = 0.01

        # Compute pairwise forces → curvature (only nearest entities for efficiency)
        field_strength: dict[str, float] = {}
        curvature: dict[str, float] = {}
        entity_list = list(visited)[:max_entities]

        for i, a in enumerate(entity_list):
            total_force = 0.0
            total_curv = 0.0
            mass_a = masses[a].raw_mass
            for b in entity_list:
                if a == b:
                    continue
                mass_b = masses[b].raw_mass
                distance = self._semantic_distance(a, b)
                # Gravity: F = G × M_a × M_b / r²
                # With smooth cutoff: r_min = 0.1 prevents singularity
                r = max(0.1, distance)
                force = self.G_KNOWLEDGE * mass_a * mass_b / (r * r)
                total_force += force
                total_curv += force * r  # Curvature contribution
            field_strength[a] = total_force
            curvature[a] = total_curv

        # Total entropy: S = -Σ p_i log p_i where p_i = M_i / Σ M_j
        total_mass = sum(m.raw_mass for m in masses.values())
        entropy = 0.0
        if total_mass > 0:
            for m in masses.values():
                p = m.raw_mass / total_mass
                if p > 0:
                    entropy -= p * math.log(p)
        entropy = entropy / math.log(max(2, len(masses))) if len(masses) > 1 else 0.0

        # Dominant cluster: entity with max curvature
        dominant = max(curvature, key=curvature.get) if curvature else ""

        for eid in seed_entities:
            self._access_count[eid] = self._access_count.get(eid, 0) + 1
            self._last_access[eid] = time.time()

        field = GravityField(
            field_id=field_id,
            seed_entities=list(seed_entities),
            masses=masses,
            field_strength=field_strength,
            curvature=curvature,
            total_entropy=round(entropy, 4),
            dominant_cluster=dominant,
        )
        self._field_cache[field_id] = field
        return field

    # ── Gravitational Lensing ──

    def lens_trajectory(
        self,
        candidates: list[tuple[str, float]],   # (entity_id, relevance_score)
        field: GravityField,
        lens_strength: float = 0.3,           # How much the field bends the path
    ) -> list[tuple[str, float]]:
        """Bend retrieval trajectory through the knowledge gravity field.

        Gravitational lensing analog:
          - Photons (retrieval candidates) travel through curved spacetime (the field)
          - Their path bends toward regions of high curvature
          - The final ordering reflects the true knowledge topology

        Result score = (1 - lens) × relevance + lens × gravity_score
        where gravity_score ∝ field_strength(entity) × curvature(entity)
        """
        if not candidates or not field.field_strength:
            return candidates

        max_force = max(field.field_strength.values(), default=1.0)
        max_curv = max(field.curvature.values(), default=1.0)

        lensed: list[tuple[str, float]] = []
        for entity_id, relevance in candidates:
            force = field.field_strength.get(entity_id, 0)
            curv = field.curvature.get(entity_id, 0)
            # Gravity score: weighted product of normalized force and curvature
            grav_score = (force / max(max_force, 0.01)) * (curv / max(max_curv, 0.01))
            grav_score = max(0.0, min(1.0, grav_score))

            blended = relevance * (1 - lens_strength) + grav_score * lens_strength
            lensed.append((entity_id, round(blended, 4)))

        lensed.sort(key=lambda x: -x[1])
        return lensed

    # ── Event Horizon Detection ──

    def detect_event_horizon(
        self, field: GravityField, threshold: float = 0.8,
    ) -> list[str]:
        """Detect entities beyond the "event horizon" — unreachable knowledge.

        Entities with curvature below threshold relative to the dominant cluster
        are in knowledge shadows (too semantically distant for current query).
        """
        if not field.curvature or not field.dominant_cluster:
            return []

        max_curv = max(field.curvature.values(), default=1.0)
        horizon = threshold * max_curv

        shadows = [
            eid for eid, curv in field.curvature.items()
            if curv < horizon and eid not in field.seed_entities
        ]

        if shadows:
            logger.debug(f"Gravity: {len(shadows)} entities beyond event horizon (curv < {horizon:.1f})")

        return shadows

    # ── Field Analysis ──

    def field_stats(self, field: GravityField) -> dict[str, Any]:
        """Analyze a gravity field for insights."""
        if not field.masses:
            return {"empty": True}
        masses = [m.raw_mass for m in field.masses.values()]
        curvs = list(field.curvature.values())
        return {
            "entity_count": len(field.masses),
            "total_mass": round(sum(masses), 2),
            "avg_mass": round(sum(masses) / len(masses), 3),
            "max_curvature": round(max(curvs, default=0), 3),
            "entropy": field.total_entropy,
            "dominant": field.dominant_cluster[:30] if field.dominant_cluster else "",
            "seed_count": len(field.seed_entities),
        }

    def set_embedding(self, entity_id: str, embedding: list[float]) -> None:
        """Register an entity's embedding for precise distance computation."""
        self._entity_embeddings[entity_id] = embedding

    @property
    def hypergraph(self):
        return self._hg


# ═══ Static Helper: Entropy from any distribution ═══

def distribution_entropy(values: list[float]) -> float:
    """Shannon entropy of a probability-like distribution.

    S = -Σ p_i log p_i, with p_i = v_i / Σ v_j
    """
    total = sum(values)
    if total <= 0:
        return 0.0
    entropy = 0.0
    for v in values:
        if v > 0:
            p = v / total
            entropy -= p * math.log(p)
    n = len(values)
    return entropy / math.log(max(2, n)) if n > 1 else 0.0


# ═══ Singleton ═══

_gravity_model: KnowledgeGravity | None = None


def get_gravity_model(hg=None) -> KnowledgeGravity:
    global _gravity_model
    if _gravity_model is None:
        _gravity_model = KnowledgeGravity(hg)
    elif hg and not _gravity_model._hg:
        _gravity_model._hg = hg
    return _gravity_model


__all__ = [
    "KnowledgeGravity", "KnowledgeMass", "GravityField", "GravityForce",
    "distribution_entropy", "get_gravity_model",
]
