"""Services Package - 服务层包"""
from .auth_service import (
    AuthService,
    get_auth_service,
    require_auth,
    require_scope,
)
from .ws_service import (
    WebSocketRelayService,
    get_ws_relay_service,
    websocket_endpoint,
    ConnectionInfo,
    Channel,
)
from .blog_forum_api import (
    RelayBlogForumService,
    ContentItem,
    ContentType,
    ContentStatus,
    Author,
    router as blogforum_router,
)
from .enterprise_license_service import (
    EnterpriseLicenseService,
    EnterpriseInfo,
    LicenseRecord,
    LicenseStore,
    LicenseType,
    LicenseStatus,
    get_license_service,
)
from .user_auth_service import (
    UserAuthService,
    NodeService,
    PaymentGateway,
    User,
    Node,
    PaymentOrder,
    AuthProvider,
    NodeStatus,
    PaymentStatus,
    get_auth_service as get_user_auth_service,
    get_node_service,
    get_payment_gateway,
)
from .payment_gateway import (
    UnifiedPaymentGateway,
    PaymentPlatform,
    PayStatus,
    PaymentOrder as PayOrder,
    PaymentStorage,
    get_payment_gateway as get_unified_payment_gateway,
)
from .credit_recharge_service import (
    CreditRechargeService,
    CreditAccount,
    CreditTransaction,
    CreditConfig,
    VIPLevel,
    TransactionType,
    DailyBonusRecord,
    get_credit_service,
    get_credit_storage,
    get_credit_config,
    calculate_vip_level,
)
from .admin_notification_service import (
    AdminNotificationService,
    AdminOnlineManager,
    SerialRequestNotifier,
    CreditConsistencyManager,
    NotificationType,
    NotificationPriority,
    NotificationMessage,
    AdminNodeStatus,
    get_admin_notification_service,
    get_admin_online_manager,
    get_serial_request_notifier,
    get_credit_consistency_manager,
)
from .credit_sync_client import (
    CreditSyncClient,
    CreditClient,
    LocalCreditCache,
    CreditOperation,
    SyncStatus,
)
from .serial_notification_service import (
    SerialNotificationService,
    SerialDeliveryService,
    NotificationChannel,
    NotificationResult,
    NotificationRecord,
    SerialRequestRecord,
    SMSServiceInterface,
    EmailServiceInterface,
    MockSMSService,
    MockEmailService,
    get_serial_notification_service,
    get_serial_delivery_service,
)

__all__ = [
    # Auth
    "AuthService",
    "get_auth_service",
    "require_auth",
    "require_scope",
    # WebSocket
    "WebSocketRelayService",
    "get_ws_relay_service",
    "websocket_endpoint",
    "ConnectionInfo",
    "Channel",
    # Blog & Forum
    "RelayBlogForumService",
    "ContentItem",
    "ContentType",
    "ContentStatus",
    "Author",
    "blogforum_router",
    # Enterprise License
    "EnterpriseLicenseService",
    "EnterpriseInfo",
    "LicenseRecord",
    "LicenseStore",
    "LicenseType",
    "LicenseStatus",
    "get_license_service",
    # User Auth & Node
    "UserAuthService",
    "NodeService",
    "PaymentGateway",
    "User",
    "Node",
    "PaymentOrder",
    "AuthProvider",
    "NodeStatus",
    "PaymentStatus",
    "get_user_auth_service",
    "get_node_service",
    "get_payment_gateway",
    # Payment Gateway
    "UnifiedPaymentGateway",
    "PaymentPlatform",
    "PayStatus",
    "PayOrder",
    "PaymentStorage",
    "get_unified_payment_gateway",
    # Credit Recharge & VIP
    "CreditRechargeService",
    "CreditAccount",
    "CreditTransaction",
    "CreditConfig",
    "VIPLevel",
    "TransactionType",
    "DailyBonusRecord",
    "get_credit_service",
    "get_credit_storage",
    "get_credit_config",
    "calculate_vip_level",
    # Admin Notification
    "AdminNotificationService",
    "AdminOnlineManager",
    "SerialRequestNotifier",
    "CreditConsistencyManager",
    "NotificationType",
    "NotificationPriority",
    "NotificationMessage",
    "AdminNodeStatus",
    "get_admin_notification_service",
    "get_admin_online_manager",
    "get_serial_request_notifier",
    "get_credit_consistency_manager",
    # Credit Sync Client
    "CreditSyncClient",
    "CreditClient",
    "LocalCreditCache",
    "CreditOperation",
    "SyncStatus",
    # Serial Notification
    "SerialNotificationService",
    "SerialDeliveryService",
    "NotificationChannel",
    "NotificationResult",
    "NotificationRecord",
    "SerialRequestRecord",
    "SMSServiceInterface",
    "EmailServiceInterface",
    "MockSMSService",
    "MockEmailService",
    "get_serial_notification_service",
    "get_serial_delivery_service",
]
