"""Self-Play Skill Discovery — Ctx2Skill-inspired autonomous skill extraction.

Based on arXiv:2604.27660 (Si et al., THU/UIUC 2026):
  "From Context to Skills: Can Language Models Learn from Context Skillfully?"

Core insight: Skills don't need to be manually annotated. A 5-agent self-play loop
can autonomously extract context-specific skills from complex contexts.

Design (adapted to LivingTree):
  1. CONTEXT → Challenger generates probing tasks based on retrieved knowledge
  2. Reasoner attempts tasks guided by current skill set
  3. Judge provides binary pass/fail → routes to Proposer
  4. Proposer analyzes failures → proposes skill updates
  5. Generator materializes proposals into natural-language skills
  6. Cross-Time Replay selects most generalizable skill set

Integration: Called after each retrieval cycle in intelligent_kb.py.
"""

from __future__ import annotations

import json
import time
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from loguru import logger


# ── Data Types ──

@dataclass
class SkillProbe:
    """A probing task generated by the Challenger."""
    task: str
    rubric: str          # How to judge success
    context_source: str   # Which retrieved context spawned this
    difficulty: float = 0.5
    timestamp: float = field(default_factory=time.time)


@dataclass
class SkillMatch:
    """A skill applied to solve a task."""
    skill_name: str
    skill_content: str
    probe: SkillProbe
    success: bool = False
    judge_reason: str = ""


@dataclass
class DiscoveredSkill:
    """A skill extracted from context via self-play."""
    name: str
    content: str          # Natural language skill description
    source_context: str = ""  # Which context spawned this
    proven_on: list[str] = field(default_factory=list)  # Probe IDs it solved
    confidence: float = 0.5
    iteration: int = 0
    timestamp: float = field(default_factory=time.time)


class SelfPlaySkillDiscoverer:
    """Autonomous skill discovery through multi-agent self-play.

    Replaces the hardcoded SYSTEM_TOOLS with dynamically discovered
    context-specific skills extracted from retrieval results.
    """

    def __init__(self, store_path: str = ".livingtree/discovered_skills.json"):
        self._store_path = Path(store_path)
        self._discovered: dict[str, DiscoveredSkill] = {}
        self._probes: list[SkillProbe] = []
        self._history: list[SkillMatch] = []
        self._iteration = 0
        self._load()

    # ── Step 1: Generate probes from context ──

    def generate_probes(self, context_text: str, source: str, n: int = 3) -> list[SkillProbe]:
        """Challenger: generate probing tasks from retrieved context.

        These probes test whether the system truly understands the context,
        not just pattern-matches surface keywords.
        """
        probes = []
        lines = context_text.split("\n")

        for i in range(min(n, max(1, len(lines) // 5))):
            start = i * 5
            segment = "\n".join(lines[start:start + 10])

            if len(segment.strip()) < 50:
                continue

            # Extract key entities/concepts from segment for probing
            probe = SkillProbe(
                task=f"Explain the relationship between concepts in: {segment[:150]}...",
                rubric="Response must demonstrate understanding of causal/logical relationships.",
                context_source=source,
                difficulty=0.4 + (i * 0.15),
            )
            probes.append(probe)

        self._probes.extend(probes)
        return probes

    # ── Step 2: Attempt with current skills ──

    def attempt_with_skills(self, probe: SkillProbe, available_skills: dict) -> SkillMatch:
        """Reasoner: try to solve a probe using available skills.

        Returns a SkillMatch indicating success/failure.
        """
        # Find most relevant skill
        best_skill_name = None
        best_skill_content = ""
        best_score = 0

        for name, content in available_skills.items():
            score = self._skill_probe_match(content, probe.task)
            if score > best_score:
                best_score = score
                best_skill_name = name
                best_skill_content = content

        # Judge: simulate success check
        # In production, this would involve actual LLM verification
        success = best_score > 0.3

        match = SkillMatch(
            skill_name=best_skill_name or "unknown",
            skill_content=best_skill_content,
            probe=probe,
            success=success,
            judge_reason=f"Skill match score: {best_score:.2f}",
        )

        self._history.append(match)
        return match

    # ── Step 3: Proposer + Generator — extract skills from failures ──

    def extract_skill_from_failure(self, match: SkillMatch, context: str) -> Optional[DiscoveredSkill]:
        """Proposer + Generator: analyze a failure and synthesize a new skill.

        The paper's key innovation: failure cases drive skill discovery.
        """
        if match.success:
            return None

        # Generate skill name from probe task
        task_words = match.probe.task.lower().split()
        key_concepts = [w for w in task_words if len(w) > 4 and w.isalpha()][:3]
        if not key_concepts:
            key_concepts = ["context", "reasoning"]

        skill_name = f"skill_{'_'.join(key_concepts[:2])}"

        # Skip if already discovered
        if skill_name in self._discovered:
            return None

        # Generate skill content from the context that spawned this probe
        # Extract relevant sentences from context
        context_sentences = context.split(".")
        relevant = []
        for sent in context_sentences[:10]:
            if any(kw in sent.lower() for kw in key_concepts):
                relevant.append(sent.strip())

        skill_content = (
            f"Skill for {match.probe.task[:80]}.\n"
            f"Key context:\n" + "\n".join(f"- {s}" for s in relevant[:5]) +
            f"\n\nTask: {match.probe.task}\n"
            f"Rubric: {match.probe.rubric}"
        )

        discovered = DiscoveredSkill(
            name=skill_name,
            content=skill_content[:500],
            source_context=match.probe.context_source,
            proven_on=[],
            confidence=0.3,  # Low confidence until proven
            iteration=self._iteration,
        )

        self._discovered[skill_name] = discovered
        self._save()

        logger.info(
            f"SelfPlaySkill: discovered '{skill_name}' from failure "
            f"on context '{match.probe.context_source[:40]}'"
        )
        return discovered

    # ── Step 4: Cross-Time Replay — prevent adversarial collapse ──

    def cross_time_replay(self) -> dict[str, DiscoveredSkill]:
        """Replay historical probes and select the most generalizable skill set.

        This prevents over-specialization and adversarial collapse
        (the paper's key stability mechanism).
        """
        if not self._probes or not self._discovered:
            return dict(self._discovered)

        # Score each discovered skill against ALL historical probes
        skill_scores: dict[str, list[float]] = defaultdict(list)

        for name, skill in self._discovered.items():
            for probe in self._probes[-20:]:  # Last 20 probes
                score = self._skill_probe_match(skill.content, probe.task)
                skill_scores[name].append(score)

        # Select top-N skills with best average scores
        avg_scores = {
            name: sum(scores) / len(scores)
            for name, scores in skill_scores.items()
        }
        sorted_skills = sorted(avg_scores.items(), key=lambda x: -x[1])

        # Keep top 50%
        top_half = dict(sorted_skills[:max(1, len(sorted_skills) // 2)])
        selected = {
            name: self._discovered[name]
            for name in top_half
        }

        # Prune the rest
        removed = set(self._discovered.keys()) - set(selected.keys())
        for name in removed:
            logger.debug(f"CrossTimeReplay: pruning over-specialized skill '{name}'")
            del self._discovered[name]

        self._save()
        return selected

    # ── Full Pipeline ──

    def discover_from_context(
        self, context_text: str, source: str, existing_skills: dict = None
    ) -> dict[str, DiscoveredSkill]:
        """Run full self-play discovery pipeline on a retrieved context.

        Args:
            context_text: Retrieved knowledge context.
            source: Context source identifier.
            existing_skills: Currently available skills.

        Returns:
            Dict of newly discovered skills.
        """
        self._iteration += 1
        existing = existing_skills or {
            name: skill.content
            for name, skill in self._discovered.items()
        }

        # Step 1: Generate probes
        probes = self.generate_probes(context_text, source)

        # Step 2-3: Attempt → discover from failures
        new_skills = {}
        for probe in probes:
            match = self.attempt_with_skills(probe, existing)
            if not match.success:
                discovered = self.extract_skill_from_failure(match, context_text)
                if discovered:
                    new_skills[discovered.name] = discovered
                    # Update existing skills for subsequent probes
                    existing[discovered.name] = discovered.content

        # Step 4: Cross-time replay every 5 iterations
        if self._iteration % 5 == 0:
            self.cross_time_replay()

        return new_skills

    # ── Query ──

    def get_all_skills(self) -> dict[str, str]:
        return {name: skill.content for name, skill in self._discovered.items()}

    def get_top_skills(self, n: int = 10) -> list[dict]:
        sorted_skills = sorted(
            self._discovered.values(),
            key=lambda s: (s.confidence, len(s.proven_on)),
            reverse=True,
        )
        return [
            {"name": s.name, "content": s.content, "confidence": s.confidence}
            for s in sorted_skills[:n]
        ]

    # ── Internal ──

    def _skill_probe_match(self, skill_content: str, probe_task: str) -> float:
        """Compute how well a skill matches a probe task."""
        if not skill_content or not probe_task:
            return 0.0
        skill_words = set(skill_content.lower().split())
        task_words = set(probe_task.lower().split())
        if not task_words:
            return 0.0
        overlap = skill_words & task_words
        return len(overlap) / len(task_words)

    def _load(self) -> None:
        try:
            if self._store_path.exists():
                data = json.loads(self._store_path.read_text("utf-8"))
                for name, entry in data.get("skills", {}).items():
                    self._discovered[name] = DiscoveredSkill(**entry)
        except Exception:
            pass

    def _save(self) -> None:
        try:
            self._store_path.parent.mkdir(parents=True, exist_ok=True)
            data = {
                "skills": {
                    name: {
                        "name": s.name,
                        "content": s.content,
                        "source_context": s.source_context,
                        "confidence": s.confidence,
                        "iteration": s.iteration,
                    }
                    for name, s in self._discovered.items()
                },
                "iteration": self._iteration,
            }
            self._store_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), "utf-8")
        except Exception:
            pass


# ── Singleton ──

_discoverer: Optional[SelfPlaySkillDiscoverer] = None


def get_skill_discoverer() -> SelfPlaySkillDiscoverer:
    global _discoverer
    if _discoverer is None:
        _discoverer = SelfPlaySkillDiscoverer()
    return _discoverer
