"""Scinet Service — Local Smart Proxy for overseas site access (学习用途).

Implements a lightweight local HTTP/HTTPS proxy that:
  1. Routes overseas domain requests through optimal IPs (DomainIPPool)
  2. Uses proxy chain fallback (ProxyPool) for blocked sites
  3. Generates PAC (Proxy Auto-Config) file for browser config
  4. Supports /scinet start | stop | status commands
  5. Integrates with SiteAccelerator for zero-latency routing

Architecture:
  Browser → localhost:7890 (Scinet) → 最优IP直连 or 代理链 → 海外站点

Commands:
  /scinet start    — 启动代理服务
  /scinet stop     — 停止代理服务
  /scinet status   — 查看服务状态
  /scinet pac      — 获取PAC文件URL
  /scinet test     — 测试连接
"""

from __future__ import annotations

import asyncio
import json
import os
import socket
import ssl
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from loguru import logger

try:
    import aiohttp
    from aiohttp import web
    HAS_AIOHTTP = True
except ImportError:
    HAS_AIOHTTP = False


@dataclass
class ScinetStatus:
    """Scinet service status snapshot."""
    running: bool = False
    port: int = 7890
    pac_url: str = ""
    uptime_seconds: float = 0.0
    total_requests: int = 0
    success_requests: int = 0
    failed_requests: int = 0
    active_connections: int = 0
    accelerated_domains: int = 0
    bandwidth_bytes: int = 0


# ═══ PAC File Generator ═══

PAC_TEMPLATE = """function FindProxyForURL(url, host) {{
    // Scinet PAC — Auto-generated by LivingTree
    // 直接访问: 国内站点（绕过代理）
    // 代理访问: 海外站点

    // 国内域名直连
    if (shExpMatch(host, "*.cn") ||
        shExpMatch(host, "*.com.cn") ||
        shExpMatch(host, "*.org.cn") ||
        shExpMatch(host, "*.edu.cn") ||
        shExpMatch(host, "*.gov.cn") ||
        isPlainHostName(host) ||
        dnsDomainIs(host, ".local") ||
        shExpMatch(host, "127.0.0.1") ||
        shExpMatch(host, "::1") ||
        shExpMatch(host, "localhost") ||
        shExpMatch(host, "192.168.*") ||
        shExpMatch(host, "10.*") ||
        shExpMatch(host, "172.16.*")) {{
        return "DIRECT";
    }}

    // 以下域名通过Scinet代理加速
{accelerated_domains}

    // 默认: 海外站点走代理
    return "PROXY 127.0.0.1:{port}; DIRECT";
}}"""


class ScinetService:
    """本地智能代理服务 — 科学上网 (学习用途)。

    Usage:
        scinet = ScinetService(port=7890)
        await scinet.start()
        # 浏览器设置代理: 127.0.0.1:7890 或 PAC: http://127.0.0.1:{port}/pac
        await scinet.stop()
    """

    def __init__(self, port: int = 7890):
        self.port = port
        self._status = ScinetStatus(port=port)
        self._lock = threading.RLock()
        self._runner: Optional[web.AppRunner] = None
        self._site: Optional[web.TCPSite] = None
        self._raw_server: Optional[asyncio.AbstractServer] = None
        self._start_time: float = 0.0
        self._running = False

        # Subsystem refs (lazy)
        self._ip_pool: Any = None
        self._proxy_pool: Any = None
        self._accelerator: Any = None

        # Scinet v2.0 Engine (RL + GNN + Federated + QUIC + Cache + WebTransport)
        self._engine: Any = None
        self._v2_enabled: bool = False

    async def start(self) -> ScinetStatus:
        """Start Scinet proxy service using raw TCP server for full proxy support."""
        if self._running:
            logger.info("Scinet: already running on port %d", self.port)
            return self._status

        # Init subsystems (v1.0 IP pool + v2.0 engine)
        await self._init_subsystems()

        try:
            self._raw_server = await asyncio.start_server(
                self._handle_client, "127.0.0.1", self.port,
            )
        except OSError as e:
            logger.error("Scinet: port %d already in use — %s", self.port, e)
            raise RuntimeError(f"Port {self.port} occupied: {e}") from e

        self._start_time = time.time()
        self._running = True

        with self._lock:
            self._status.running = True
            self._status.uptime_seconds = 0
            self._status.pac_url = f"http://127.0.0.1:{self.port}/pac"

        logger.info("Scinet: started on http://127.0.0.1:%d", self.port)
        logger.info("  PAC URL: http://127.0.0.1:%d/pac", self.port)
        logger.info("  Test:    curl -x http://127.0.0.1:%d https://github.com", self.port)
        return self._status

    async def stop(self) -> ScinetStatus:
        """Stop Scinet proxy service."""
        if not self._running:
            return self._status

        if self._raw_server:
            self._raw_server.close()
            await self._raw_server.wait_closed()
        self._raw_server = None
        self._running = False

        # Stop v2.0 engine
        if self._engine:
            try:
                await self._engine.stop()
            except Exception as e:
                logger.debug("Scinet engine stop: %s", e)

        with self._lock:
            self._status.running = False
            self._status.uptime_seconds = time.time() - self._start_time

        logger.info("Scinet: stopped (uptime=%.0fs, requests=%d)",
                   self._status.uptime_seconds, self._status.total_requests)
        return self._status

    # ═══ Raw TCP Client Handler (HTTP proxy + CONNECT tunnel + management) ═══

    async def _handle_client(self, reader: asyncio.StreamReader,
                             writer: asyncio.StreamWriter) -> None:
        """Process one client connection — parse HTTP, route proxy or management."""
        try:
            request_line = await asyncio.wait_for(reader.readline(), timeout=30.0)
            if not request_line:
                writer.close()
                return

            request_text = request_line.decode("utf-8", errors="replace").strip()
            if not request_text:
                writer.close()
                return

            parts = request_text.split(" ")
            if len(parts) < 3:
                writer.close()
                return

            method, target, _ = parts

            # Read headers
            headers = {}
            while True:
                line = await asyncio.wait_for(reader.readline(), timeout=10.0)
                line_text = line.decode("utf-8", errors="replace").strip()
                if not line_text:
                    break
                if ":" in line_text:
                    key, value = line_text.split(":", 1)
                    headers[key.strip()] = value.strip()

            # Route: CONNECT → tunnel, GET /pac etc → management, other → proxy
            if method == "CONNECT":
                await self._raw_connect_tunnel(target, reader, writer)
            elif target.startswith("http://") or target.startswith("https://"):
                # HTTP proxy: full URL in request line
                await self._raw_proxy_forward(method, target, headers, reader, writer)
            else:
                # Management endpoints (relative path)
                await self._raw_management(method, target, headers, reader, writer)

        except asyncio.TimeoutError:
            pass
        except ConnectionError:
            pass
        except Exception as e:
            logger.debug("Client handler error: %s", e)
        finally:
            try:
                writer.close()
            except Exception:
                pass

    async def _raw_connect_tunnel(self, target: str, reader: asyncio.StreamReader,
                                   writer: asyncio.StreamWriter) -> None:
        """Handle CONNECT method — direct connect with proxy pool fallback."""
        if ":" in target:
            host, port_str = target.rsplit(":", 1)
            try:
                port = int(port_str)
            except ValueError:
                host, port = target, 443
        else:
            host, port = target, 443

        logger.info("CONNECT tunnel: %s:%d", host, port)

        remote_reader, remote_writer = await self._connect_with_fallback(host, port)

        if remote_reader is None:
            logger.debug("CONNECT %s:%d failed (direct + proxy)", host, port)
            writer.write(b"HTTP/1.1 502 Bad Gateway\r\n\r\n")
            await writer.drain()
            return

        # Send 200 to client
        writer.write(b"HTTP/1.1 200 Connection Established\r\n")
        writer.write(b"Proxy-Agent: LivingTree-Scinet/2.0\r\n\r\n")
        await writer.drain()

        with self._lock:
            self._status.total_requests += 1

        # Bidirectional relay
        try:
            async def pipe(src_r, dst_w, label):
                try:
                    while True:
                        data = await src_r.read(65536)
                        if not data:
                            break
                        dst_w.write(data)
                        await dst_w.drain()
                except Exception:
                    pass

            await asyncio.gather(
                pipe(reader, remote_writer, "c2r"),
                pipe(remote_reader, writer, "r2c"),
            )
        except Exception:
            pass
        finally:
            with self._lock:
                self._status.success_requests += 1
            if remote_writer:
                remote_writer.close()

    async def _connect_with_fallback(self, host: str, port: int):
        """Try direct connect, then proxy pool, then DomainIPPool."""
        # 0. ScinetHardener proxy fallback
        try:
            from .scinet_hardening import get_scinet_hardener
            hardener = get_scinet_hardener()
            result = await hardener.execute("CONNECT", f"{host}:{port}")
            if result and result.get("ok"):
                return result["connection"]
        except Exception:
            pass

        # 1. Direct connection
        try:
            r, w = await asyncio.wait_for(
                asyncio.open_connection(host, port), timeout=10.0,
            )
            logger.debug("CONNECT %s:%d → direct", host, port)
            return r, w
        except Exception:
            pass

        # 2. Domain IP Pool (pre-tested optimal IPs)
        if self._ip_pool:
            best_ip = self._ip_pool.get_best(host)
            if best_ip and best_ip.ip != host:
                try:
                    r, w = await asyncio.wait_for(
                        asyncio.open_connection(best_ip.ip, port), timeout=10.0,
                    )
                    logger.info("CONNECT %s:%d → optimal IP %s", host, port, best_ip.ip)
                    return r, w
                except Exception:
                    pass

        # 3. Proxy pool (free proxies)
        if self._proxy_pool:
            for _ in range(3):
                proxy = self._proxy_pool.get_random()
                if not proxy:
                    break
                try:
                    r, w = await self._http_connect_via_proxy(
                        proxy.host, proxy.port, host, port,
                    )
                    if r:
                        logger.info("CONNECT %s:%d → proxy %s:%d", host, port, proxy.host, proxy.port)
                        self._proxy_pool.mark_success(proxy)
                        return r, w
                    self._proxy_pool.mark_failure(proxy)
                except Exception:
                    self._proxy_pool.mark_failure(proxy)

        return None, None

    async def _http_connect_via_proxy(self, proxy_host: str, proxy_port: int,
                                       target_host: str, target_port: int):
        """Establish tunnel to target through an upstream HTTP proxy."""
        try:
            r, w = await asyncio.wait_for(
                asyncio.open_connection(proxy_host, proxy_port), timeout=8.0,
            )
            # Send CONNECT to upstream proxy
            w.write(f"CONNECT {target_host}:{target_port} HTTP/1.1\r\n".encode())
            w.write(f"Host: {target_host}:{target_port}\r\n".encode())
            w.write(b"Proxy-Connection: Keep-Alive\r\n")
            w.write(b"User-Agent: LivingTree-Scinet/2.0\r\n\r\n")
            await w.drain()

            # Read response
            line = await asyncio.wait_for(r.readline(), timeout=5.0)
            parts = line.decode().split()
            if len(parts) >= 2 and parts[1] == "200":
                # Read remaining headers
                while True:
                    l = await asyncio.wait_for(r.readline(), timeout=3.0)
                    if l.strip() == b"":
                        break
                return r, w
            w.close()
        except Exception:
            pass
        return None, None

    async def _raw_proxy_forward(self, method: str, target_url: str,
                                  headers: dict, reader: asyncio.StreamReader,
                                  writer: asyncio.StreamWriter) -> None:
        """Forward HTTP proxy request to target and relay response."""
        with self._lock:
            self._status.total_requests += 1

        # Read body if present
        body = b""
        if method in ("POST", "PUT", "PATCH"):
            content_length = int(headers.get("Content-Length", "0"))
            if content_length > 0 and content_length < 10 * 1024 * 1024:
                body = await asyncio.wait_for(
                    reader.readexactly(content_length), timeout=10.0,
                )

        # Clean headers
        clean_headers = dict(headers)
        for h in ("Host", "Proxy-Connection", "Proxy-Authorization",
                  "X-Forwarded-For", "X-Real-IP", "Content-Length",
                  "Transfer-Encoding", "Proxy-Authenticate"):
            clean_headers.pop(h, None)
        clean_headers["User-Agent"] = clean_headers.get("User-Agent", "LivingTree-Scinet/2.0")
        clean_headers["Accept-Encoding"] = clean_headers.get("Accept-Encoding", "identity")

        # Domain category
        domain_category = "GENERAL"
        try:
            from urllib.parse import urlparse
            hostname = urlparse(target_url).hostname or ""
            if any(d in hostname for d in ("github", "huggingface", "docker", "pypi")):
                domain_category = "DEDICATED"
            elif any(d in hostname for d in ("google", "stackoverflow", "wikipedia", "arxiv")):
                domain_category = "SEARCH"
            elif any(d in hostname for d in ("youtube", "googlevideo")):
                domain_category = "VIDEO"
        except Exception:
            pass

        # v2.0 engine pipeline
        if self._v2_enabled and self._engine:
            try:
                status_code, content, resp_headers = await self._engine.proxy_request(
                    target_url, method=method, headers=clean_headers,
                    body=body, timeout=30.0,
                    domain_category=domain_category,
                )
                with self._lock:
                    self._status.success_requests += 1
                    self._status.bandwidth_bytes += len(content)

                response_line = f"HTTP/1.1 {status_code} OK\r\n".encode()
                writer.write(response_line)
                writer.write(b"X-Proxy: LivingTree-Scinet/2.0\r\n")
                writer.write(b"X-Routing: bandit+topology+quic\r\n")
                writer.write(f"Content-Length: {len(content)}\r\n".encode())
                if resp_headers:
                    content_type = resp_headers.get("Content-Type", "text/html")
                    writer.write(f"Content-Type: {content_type}\r\n".encode())
                writer.write(b"Access-Control-Allow-Origin: *\r\n")
                writer.write(b"Connection: close\r\n\r\n")
                writer.write(content)
                await writer.drain()
                return
            except Exception as e:
                logger.debug("v2.0 engine failed, fallback v1.0: %s", e)

        # v1.0 direct forwarding
        try:
            connector = aiohttp.TCPConnector(limit=50)
            async with aiohttp.ClientSession(connector=connector) as session:
                async with session.request(
                    method, target_url,
                    headers=clean_headers,
                    data=body,
                    timeout=aiohttp.ClientTimeout(total=30),
                    allow_redirects=True,
                ) as resp:
                    content = await resp.read()
                    with self._lock:
                        self._status.success_requests += 1
                        self._status.bandwidth_bytes += len(content)

                    writer.write(f"HTTP/1.1 {resp.status} {resp.reason}\r\n".encode())
                    writer.write(b"X-Proxy: LivingTree-Scinet/1.0\r\n")
                    for hdr, val in resp.headers.items():
                        if hdr.lower() not in ("transfer-encoding", "content-encoding"):
                            writer.write(f"{hdr}: {val}\r\n".encode())
                    writer.write(b"Connection: close\r\n\r\n")
                    writer.write(content)
                    await writer.drain()
        except Exception as e:
            with self._lock:
                self._status.failed_requests += 1
            logger.debug("Proxy error: %s → %s", target_url[:80], e)
            writer.write(b"HTTP/1.1 502 Bad Gateway\r\n")
            writer.write(f"X-Proxy-Error: {e}\r\n".encode())
            writer.write(b"Content-Type: text/plain\r\n")
            writer.write(b"Connection: close\r\n\r\n")
            writer.write(f"Upstream error: {type(e).__name__}".encode())
            await writer.drain()

    async def _raw_management(self, method: str, path: str, headers: dict,
                               reader: asyncio.StreamReader,
                               writer: asyncio.StreamWriter) -> None:
        """Handle management endpoints: /pac, /status, /v2/status, /test, /."""
        if method != "GET":
            writer.write(b"HTTP/1.1 405 Method Not Allowed\r\n\r\n")
            await writer.drain()
            return

        path_clean = path.split("?")[0] if "?" in path else path

        if path_clean == "/":
            v2_info = " + v2.0 Engine" if self._v2_enabled else ""
            body = f"Scinet v1.0{v2_info} — LivingTree Smart Proxy\nPort: {self.port}\nPAC: http://127.0.0.1:{self.port}/pac\nV2 Status: http://127.0.0.1:{self.port}/v2/status"
        elif path_clean == "/pac":
            body = self.generate_pac()
        elif path_clean == "/status":
            import json as _json
            st = self.get_status()
            body = _json.dumps({
                "running": st.running, "port": st.port,
                "uptime_seconds": st.uptime_seconds,
                "total_requests": st.total_requests,
                "success_rate": st.success_requests / max(st.total_requests, 1),
                "bandwidth_bytes": st.bandwidth_bytes,
            })
        elif path_clean == "/v2/status":
            import json as _json
            result = {
                "version": "2.0", "running": self._running, "port": self.port,
                "total_requests": self._status.total_requests,
                "success_requests": self._status.success_requests,
                "failed_requests": self._status.failed_requests,
            }
            if self._engine:
                try:
                    result["engine"] = self._engine.get_detailed_status()
                except Exception:
                    result["engine"] = {"error": "unavailable"}
            body = _json.dumps(result, indent=2, default=str)
        elif path_clean == "/test":
            import json as _json
            results = {}
            test_urls = ["https://github.com", "https://huggingface.co"]
            for url in test_urls:
                try:
                    async with aiohttp.ClientSession() as session:
                        t0 = time.time()
                        async with session.get(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                            elapsed = (time.time() - t0) * 1000
                            results[url] = f"OK ({resp.status}, {elapsed:.0f}ms)"
                except Exception as e:
                    results[url] = f"FAIL ({e})"
            body = _json.dumps({"test_results": results})
        else:
            writer.write(b"HTTP/1.1 404 Not Found\r\n\r\nNot Found")
            await writer.drain()
            return

        body_bytes = body.encode("utf-8")
        writer.write(b"HTTP/1.1 200 OK\r\n")
        writer.write(b"Server: LivingTree-Scinet/2.0\r\n")
        writer.write(f"Content-Length: {len(body_bytes)}\r\n".encode())
        writer.write(b"Content-Type: application/json\r\n" if path_clean in ("/status", "/v2/status", "/test") else
                      b"Content-Type: application/x-ns-proxy-autoconfig\r\n" if path_clean == "/pac" else
                      b"Content-Type: text/plain\r\n")
        writer.write(b"Connection: close\r\n\r\n")
        writer.write(body_bytes)
        await writer.drain()

    def get_status(self) -> ScinetStatus:
        with self._lock:
            if self._running:
                self._status.uptime_seconds = time.time() - self._start_time
            return self._status

    def generate_pac(self) -> str:
        """生成PAC文件内容。"""
        domains = []
        try:
            from .domain_ip_pool import DomainIPPool
            pool = DomainIPPool()
            for cat in ["DEDICATED", "SEARCH", "CDN", "VIDEO"]:
                for domain in pool.get_domains_by_category(cat):
                    domains.append(f'    if (dnsDomainIs(host, "{domain}")) return "PROXY 127.0.0.1:{self.port}; DIRECT";')
        except Exception:
            pass

        accelerated = "\n".join(domains) if domains else "    // No accelerated domains configured"
        return PAC_TEMPLATE.format(
            port=self.port,
            accelerated_domains=accelerated,
        )

    def set_windows_proxy(self, enable: bool) -> bool:
        """设置/清除 Windows 系统代理。

        Uses registry: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings
        """
        try:
            import winreg
            key = winreg.OpenKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Internet Settings",
                0, winreg.KEY_SET_VALUE,
            )
            if enable:
                winreg.SetValueEx(key, "ProxyEnable", 0, winreg.REG_DWORD, 1)
                winreg.SetValueEx(key, "ProxyServer", 0, winreg.REG_SZ, f"127.0.0.1:{self.port}")
                winreg.SetValueEx(key, "ProxyOverride", 0, winreg.REG_SZ, "localhost;127.*;192.168.*;10.*;*.cn;*.local")
                logger.info("Scinet: Windows system proxy enabled → 127.0.0.1:%d", self.port)
            else:
                winreg.SetValueEx(key, "ProxyEnable", 0, winreg.REG_DWORD, 0)
                logger.info("Scinet: Windows system proxy disabled")
            winreg.CloseKey(key)
            return True
        except Exception as e:
            logger.warning("Scinet: Windows proxy config failed: %s", e)
            return False

    async def _init_subsystems(self) -> None:
        try:
            from .domain_ip_pool import DomainIPPool
            self._ip_pool = DomainIPPool()
            await self._ip_pool.initialize()
        except Exception as e:
            logger.debug("Scinet: IP pool init skipped: %s", e)

        try:
            from .proxy_fetcher import get_proxy_pool
            self._proxy_pool = get_proxy_pool()
            # Start background proxy refresh + health check loop
            asyncio.create_task(self._proxy_pool.start_background())
            logger.info("Proxy pool: 6 sources, auto-refresh every 10min")
        except Exception:
            pass

        try:
            from .site_accelerator import get_accelerator
            self._accelerator = get_accelerator()
            await self._accelerator.initialize()
        except Exception:
            pass

        # Scinet v2.0 Engine — RL Bandit + GNN Topology + Federated + QUIC + Cache
        try:
            from .scinet_engine import get_scinet_engine
            self._engine = get_scinet_engine(port=self.port)
            await self._engine.start()
            self._v2_enabled = True
            logger.info("Scinet v2.0 engine activated (Bandit + Topology + Federated + QUIC + Cache)")
        except Exception as e:
            logger.debug("Scinet v2.0 engine deferred: %s", e)


# ═══ Singleton ═══

_scinet: Optional[ScinetService] = None
_scinet_lock = threading.Lock()


def get_scinet(port: int = 7890) -> ScinetService:
    global _scinet
    if _scinet is None:
        with _scinet_lock:
            if _scinet is None:
                _scinet = ScinetService(port=port)
    return _scinet
