"""Scinet Service — Local Smart Proxy for overseas site access (学习用途).

Implements a lightweight local HTTP/HTTPS proxy that:
  1. Routes overseas domain requests through optimal IPs (DomainIPPool)
  2. Uses proxy chain fallback (ProxyPool) for blocked sites
  3. Generates PAC (Proxy Auto-Config) file for browser config
  4. Supports /scinet start | stop | status commands
  5. Integrates with SiteAccelerator for zero-latency routing

Architecture:
  Browser → localhost:7890 (Scinet) → 最优IP直连 or 代理链 → 海外站点

Commands:
  /scinet start    — 启动代理服务
  /scinet stop     — 停止代理服务
  /scinet status   — 查看服务状态
  /scinet pac      — 获取PAC文件URL
  /scinet test     — 测试连接
"""

from __future__ import annotations

import asyncio
import json
import os
import socket
import ssl
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from loguru import logger

try:
    import aiohttp
    from aiohttp import web
    HAS_AIOHTTP = True
except ImportError:
    HAS_AIOHTTP = False


@dataclass
class ScinetStatus:
    """Scinet service status snapshot."""
    running: bool = False
    port: int = 7890
    pac_url: str = ""
    uptime_seconds: float = 0.0
    total_requests: int = 0
    success_requests: int = 0
    failed_requests: int = 0
    active_connections: int = 0
    accelerated_domains: int = 0
    bandwidth_bytes: int = 0


# ═══ PAC File Generator ═══

PAC_TEMPLATE = """function FindProxyForURL(url, host) {{
    // Scinet PAC — Auto-generated by LivingTree
    // 直接访问: 国内站点（绕过代理）
    // 代理访问: 海外站点

    // 国内域名直连
    if (shExpMatch(host, "*.cn") ||
        shExpMatch(host, "*.com.cn") ||
        shExpMatch(host, "*.org.cn") ||
        shExpMatch(host, "*.edu.cn") ||
        shExpMatch(host, "*.gov.cn") ||
        isPlainHostName(host) ||
        dnsDomainIs(host, ".local") ||
        shExpMatch(host, "127.0.0.1") ||
        shExpMatch(host, "::1") ||
        shExpMatch(host, "localhost") ||
        shExpMatch(host, "192.168.*") ||
        shExpMatch(host, "10.*") ||
        shExpMatch(host, "172.16.*")) {{
        return "DIRECT";
    }}

    // 以下域名通过Scinet代理加速
{accelerated_domains}

    // 默认: 海外站点走代理
    return "PROXY 127.0.0.1:{port}; DIRECT";
}}"""


class ScinetService:
    """本地智能代理服务 — 科学上网 (学习用途)。

    Usage:
        scinet = ScinetService(port=7890)
        await scinet.start()
        # 浏览器设置代理: 127.0.0.1:7890 或 PAC: http://127.0.0.1:{port}/pac
        await scinet.stop()
    """

    def __init__(self, port: int = 7890):
        self.port = port
        self._status = ScinetStatus(port=port)
        self._lock = threading.RLock()
        self._runner: Optional[web.AppRunner] = None
        self._site: Optional[web.TCPSite] = None
        self._start_time: float = 0.0
        self._running = False

        # Subsystem refs (lazy)
        self._ip_pool: Any = None
        self._proxy_pool: Any = None
        self._accelerator: Any = None

    async def start(self) -> ScinetStatus:
        """启动 Scinet 代理服务。"""
        if self._running:
            logger.info("Scinet: already running on port %d", self.port)
            return self._status

        if not HAS_AIOHTTP:
            raise RuntimeError("aiohttp required for Scinet service")

        # Init subsystems
        await self._init_subsystems()

        app = self._create_app()
        self._runner = web.AppRunner(app)
        await self._runner.setup()

        try:
            self._site = web.TCPSite(self._runner, "127.0.0.1", self.port)
            await self._site.start()
        except OSError as e:
            await self._runner.cleanup()
            self._runner = None
            logger.error("Scinet: port %d already in use — %s", self.port, e)
            raise RuntimeError(f"Port {self.port} occupied: {e}") from e

        self._start_time = time.time()
        self._running = True

        with self._lock:
            self._status.running = True
            self._status.uptime_seconds = 0
            self._status.pac_url = f"http://127.0.0.1:{self.port}/pac"

        logger.info("Scinet: started on http://127.0.0.1:%d", self.port)
        logger.info("  PAC URL: http://127.0.0.1:%d/pac", self.port)
        logger.info("  Test:    curl -x http://127.0.0.1:%d https://github.com", self.port)
        return self._status

    async def stop(self) -> ScinetStatus:
        """Stop Scinet proxy service."""
        if not self._running:
            return self._status

        try:
            if self._site:
                await self._site.stop()
        except Exception as e:
            logger.warning("Scinet stop site error: %s", e)

        try:
            if self._runner:
                await self._runner.cleanup()
        except Exception as e:
            logger.warning("Scinet stop runner error: %s", e)

        self._site = None
        self._runner = None
        self._running = False

        with self._lock:
            self._status.running = False
            self._status.uptime_seconds = time.time() - self._start_time

        logger.info("Scinet: stopped (uptime=%.0fs, requests=%d)",
                   self._status.uptime_seconds, self._status.total_requests)
        return self._status

    def get_status(self) -> ScinetStatus:
        with self._lock:
            if self._running:
                self._status.uptime_seconds = time.time() - self._start_time
            return self._status

    def generate_pac(self) -> str:
        """生成PAC文件内容。"""
        domains = []
        try:
            from .domain_ip_pool import DomainIPPool
            pool = DomainIPPool()
            for cat in ["DEDICATED", "SEARCH", "CDN", "VIDEO"]:
                for domain in pool.get_domains_by_category(cat):
                    domains.append(f'    if (dnsDomainIs(host, "{domain}")) return "PROXY 127.0.0.1:{self.port}; DIRECT";')
        except Exception:
            pass

        accelerated = "\n".join(domains) if domains else "    // No accelerated domains configured"
        return PAC_TEMPLATE.format(
            port=self.port,
            accelerated_domains=accelerated,
        )

    def set_windows_proxy(self, enable: bool) -> bool:
        """设置/清除 Windows 系统代理。

        Uses registry: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings
        """
        try:
            import winreg
            key = winreg.OpenKey(
                winreg.HKEY_CURRENT_USER,
                r"Software\Microsoft\Windows\CurrentVersion\Internet Settings",
                0, winreg.KEY_SET_VALUE,
            )
            if enable:
                winreg.SetValueEx(key, "ProxyEnable", 0, winreg.REG_DWORD, 1)
                winreg.SetValueEx(key, "ProxyServer", 0, winreg.REG_SZ, f"127.0.0.1:{self.port}")
                winreg.SetValueEx(key, "ProxyOverride", 0, winreg.REG_SZ, "localhost;127.*;192.168.*;10.*;*.cn;*.local")
                logger.info("Scinet: Windows system proxy enabled → 127.0.0.1:%d", self.port)
            else:
                winreg.SetValueEx(key, "ProxyEnable", 0, winreg.REG_DWORD, 0)
                logger.info("Scinet: Windows system proxy disabled")
            winreg.CloseKey(key)
            return True
        except Exception as e:
            logger.warning("Scinet: Windows proxy config failed: %s", e)
            return False

    # ═══ HTTP Proxy Server ═══

    def _create_app(self) -> web.Application:
        app = web.Application()
        app.router.add_get("/", self._handle_root)
        app.router.add_get("/pac", self._handle_pac)
        app.router.add_get("/status", self._handle_status)
        app.router.add_get("/test", self._handle_test)
        app.router.add_route("*", "/{path:.*}", self._handle_proxy)
        return app

    async def _handle_root(self, request: web.Request) -> web.Response:
        return web.Response(text=f"Scinet v1.0 — LivingTree Smart Proxy\nPort: {self.port}\nStatus: {'running' if self._running else 'stopped'}\nPAC: http://127.0.0.1:{self.port}/pac")

    async def _handle_pac(self, request: web.Request) -> web.Response:
        return web.Response(text=self.generate_pac(), content_type="application/x-ns-proxy-autoconfig")

    async def _handle_status(self, request: web.Request) -> web.Response:
        status = self.get_status()
        return web.json_response({
            "running": status.running,
            "port": status.port,
            "uptime_seconds": status.uptime_seconds,
            "total_requests": status.total_requests,
            "success_rate": (
                status.success_requests / max(status.total_requests, 1)
            ),
            "bandwidth_bytes": status.bandwidth_bytes,
        })

    async def _handle_test(self, request: web.Request) -> web.Response:
        """Test connectivity through the proxy."""
        results = {}
        test_urls = [
            "https://github.com",
            "https://huggingface.co",
            "https://stackoverflow.com",
            "https://www.google.com",
        ]
        for url in test_urls:
            try:
                async with aiohttp.ClientSession() as session:
                    start = time.time()
                    async with session.get(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                        elapsed = (time.time() - start) * 1000
                        results[url] = f"OK ({resp.status}, {elapsed:.0f}ms)"
            except Exception as e:
                results[url] = f"FAIL ({e})"

        return web.json_response({"test_results": results})

    async def _handle_proxy(self, request: web.Request) -> web.Response:
        """Core proxy handler — forward requests to target site."""
        with self._lock:
            self._status.total_requests += 1

        target_url = str(request.url)
        if not target_url.startswith("http"):
            proto = request.headers.get("X-Forwarded-Proto", "https")
            host = request.headers.get("Host", "")
            if not host:
                return web.Response(status=400, text="Missing Host header")
            target_url = f"{proto}://{host}{request.path_qs}"

        # Validate target URL
        if not target_url or "://" not in target_url:
            return web.Response(status=400, text="Invalid target URL")

        try:
            async with aiohttp.ClientSession() as session:
                method = request.method
                headers = dict(request.headers)
                # Sanitize headers
                for h in ("Host", "Proxy-Connection", "Proxy-Authorization",
                         "X-Forwarded-For", "X-Real-IP"):
                    headers.pop(h, None)
                headers["User-Agent"] = headers.get("User-Agent", "LivingTree-Scinet/1.0")

                # Limit body size to 10MB
                body = None
                if method in ("POST", "PUT", "PATCH"):
                    body = await asyncio.wait_for(request.read(), timeout=10.0)
                    if len(body) > 10 * 1024 * 1024:
                        return web.Response(status=413, text="Body too large")

                async with session.request(
                    method, target_url,
                    headers=headers,
                    data=body,
                    timeout=aiohttp.ClientTimeout(total=30),
                    allow_redirects=True,
                ) as resp:
                    content = await resp.read()
                    with self._lock:
                        self._status.success_requests += 1
                        self._status.bandwidth_bytes += len(content)

                    return web.Response(
                        body=content,
                        status=resp.status,
                        headers={
                            "Content-Type": resp.headers.get("Content-Type", "text/html"),
                            "X-Proxy": "LivingTree-Scinet",
                            "Access-Control-Allow-Origin": "*",
                        },
                    )

        except Exception as e:
            with self._lock:
                self._status.failed_requests += 1
            logger.debug("Scinet proxy error: %s → %s", target_url[:80], e)
            return web.Response(
                status=502,
                text=f"Proxy error: {type(e).__name__}",
                headers={"X-Proxy-Error": str(e)[:200]},
            )

    async def _init_subsystems(self) -> None:
        try:
            from .domain_ip_pool import DomainIPPool
            self._ip_pool = DomainIPPool()
            await self._ip_pool.initialize()
        except Exception as e:
            logger.debug("Scinet: IP pool init skipped: %s", e)

        try:
            from .proxy_fetcher import get_proxy_pool
            self._proxy_pool = get_proxy_pool()
        except Exception:
            pass

        try:
            from .site_accelerator import get_accelerator
            self._accelerator = get_accelerator()
            await self._accelerator.initialize()
        except Exception:
            pass


# ═══ Singleton ═══

_scinet: Optional[ScinetService] = None
_scinet_lock = threading.Lock()


def get_scinet(port: int = 7890) -> ScinetService:
    global _scinet
    if _scinet is None:
        with _scinet_lock:
            if _scinet is None:
                _scinet = ScinetService(port=port)
    return _scinet
